// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Activity {
    pub person_id: u64,
    pub activity_type: u8,
    pub started_at: f64,
    pub duration: f32,
    pub target_room_id: Option<u32>,
}

impl __sdk::InModule for Activity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Activity`.
///
/// Provides typed access to columns for query building.
pub struct ActivityCols {
    pub person_id: __sdk::__query_builder::Col<Activity, u64>,
    pub activity_type: __sdk::__query_builder::Col<Activity, u8>,
    pub started_at: __sdk::__query_builder::Col<Activity, f64>,
    pub duration: __sdk::__query_builder::Col<Activity, f32>,
    pub target_room_id: __sdk::__query_builder::Col<Activity, Option<u32>>,
}

impl __sdk::__query_builder::HasCols for Activity {
    type Cols = ActivityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActivityCols {
            person_id: __sdk::__query_builder::Col::new(table_name, "person_id"),
            activity_type: __sdk::__query_builder::Col::new(table_name, "activity_type"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            duration: __sdk::__query_builder::Col::new(table_name, "duration"),
            target_room_id: __sdk::__query_builder::Col::new(table_name, "target_room_id"),
        }
    }
}

/// Indexed column accessor struct for the table `Activity`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActivityIxCols {
    pub person_id: __sdk::__query_builder::IxCol<Activity, u64>,
}

impl __sdk::__query_builder::HasIxCols for Activity {
    type IxCols = ActivityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActivityIxCols {
            person_id: __sdk::__query_builder::IxCol::new(table_name, "person_id"),
        }
    }
}
