// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::activity_type::Activity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `activity`.
///
/// Obtain a handle from the [`ActivityTableAccess::activity`] method on [`super::RemoteTables`],
/// like `ctx.db.activity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.activity().on_insert(...)`.
pub struct ActivityTableHandle<'ctx> {
    imp: __sdk::TableHandle<Activity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `activity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActivityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ActivityTableHandle`], which mediates access to the table `activity`.
    fn activity(&self) -> ActivityTableHandle<'_>;
}

impl ActivityTableAccess for super::RemoteTables {
    fn activity(&self) -> ActivityTableHandle<'_> {
        ActivityTableHandle {
            imp: self.imp.get_table::<Activity>("activity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ActivityInsertCallbackId(__sdk::CallbackId);
pub struct ActivityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ActivityTableHandle<'ctx> {
    type Row = Activity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Activity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ActivityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActivityInsertCallbackId {
        ActivityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActivityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ActivityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActivityDeleteCallbackId {
        ActivityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActivityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Activity>("activity");
    _table.add_unique_constraint::<u64>("person_id", |row| &row.person_id);
}
pub struct ActivityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ActivityTableHandle<'ctx> {
    type UpdateCallbackId = ActivityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActivityUpdateCallbackId {
        ActivityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActivityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Activity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Activity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `person_id` unique index on the table `activity`,
/// which allows point queries on the field of the same name
/// via the [`ActivityPersonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.activity().person_id().find(...)`.
pub struct ActivityPersonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Activity, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ActivityTableHandle<'ctx> {
    /// Get a handle on the `person_id` unique index on the table `activity`.
    pub fn person_id(&self) -> ActivityPersonIdUnique<'ctx> {
        ActivityPersonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("person_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ActivityPersonIdUnique<'ctx> {
    /// Find the subscribed row whose `person_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Activity> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Activity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait activityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Activity`.
    fn activity(&self) -> __sdk::__query_builder::Table<Activity>;
}

impl activityQueryTableAccess for __sdk::QueryTableAccessor {
    fn activity(&self) -> __sdk::__query_builder::Table<Activity> {
        __sdk::__query_builder::Table::new("activity")
    }
}
