// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Conversation {
    pub id: u64,
    pub topic: u8,
    pub state: u8,
    pub started_at: f64,
    pub participant_a: u64,
    pub participant_b: u64,
}

impl __sdk::InModule for Conversation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Conversation`.
///
/// Provides typed access to columns for query building.
pub struct ConversationCols {
    pub id: __sdk::__query_builder::Col<Conversation, u64>,
    pub topic: __sdk::__query_builder::Col<Conversation, u8>,
    pub state: __sdk::__query_builder::Col<Conversation, u8>,
    pub started_at: __sdk::__query_builder::Col<Conversation, f64>,
    pub participant_a: __sdk::__query_builder::Col<Conversation, u64>,
    pub participant_b: __sdk::__query_builder::Col<Conversation, u64>,
}

impl __sdk::__query_builder::HasCols for Conversation {
    type Cols = ConversationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ConversationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            topic: __sdk::__query_builder::Col::new(table_name, "topic"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            participant_a: __sdk::__query_builder::Col::new(table_name, "participant_a"),
            participant_b: __sdk::__query_builder::Col::new(table_name, "participant_b"),
        }
    }
}

/// Indexed column accessor struct for the table `Conversation`.
///
/// Provides typed access to indexed columns for query building.
pub struct ConversationIxCols {
    pub id: __sdk::__query_builder::IxCol<Conversation, u64>,
}

impl __sdk::__query_builder::HasIxCols for Conversation {
    type IxCols = ConversationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ConversationIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
