// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Corridor {
    pub id: u64,
    pub deck: i32,
    pub corridor_type: u8,
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub length: f32,
    pub orientation: u8,
    pub carries: u8,
}

impl __sdk::InModule for Corridor {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Corridor`.
///
/// Provides typed access to columns for query building.
pub struct CorridorCols {
    pub id: __sdk::__query_builder::Col<Corridor, u64>,
    pub deck: __sdk::__query_builder::Col<Corridor, i32>,
    pub corridor_type: __sdk::__query_builder::Col<Corridor, u8>,
    pub x: __sdk::__query_builder::Col<Corridor, f32>,
    pub y: __sdk::__query_builder::Col<Corridor, f32>,
    pub width: __sdk::__query_builder::Col<Corridor, f32>,
    pub length: __sdk::__query_builder::Col<Corridor, f32>,
    pub orientation: __sdk::__query_builder::Col<Corridor, u8>,
    pub carries: __sdk::__query_builder::Col<Corridor, u8>,
}

impl __sdk::__query_builder::HasCols for Corridor {
    type Cols = CorridorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CorridorCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            deck: __sdk::__query_builder::Col::new(table_name, "deck"),
            corridor_type: __sdk::__query_builder::Col::new(table_name, "corridor_type"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            width: __sdk::__query_builder::Col::new(table_name, "width"),
            length: __sdk::__query_builder::Col::new(table_name, "length"),
            orientation: __sdk::__query_builder::Col::new(table_name, "orientation"),
            carries: __sdk::__query_builder::Col::new(table_name, "carries"),
        }
    }
}

/// Indexed column accessor struct for the table `Corridor`.
///
/// Provides typed access to indexed columns for query building.
pub struct CorridorIxCols {
    pub id: __sdk::__query_builder::IxCol<Corridor, u64>,
}

impl __sdk::__query_builder::HasIxCols for Corridor {
    type IxCols = CorridorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CorridorIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
