// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::corridor_type::Corridor;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `corridor`.
///
/// Obtain a handle from the [`CorridorTableAccess::corridor`] method on [`super::RemoteTables`],
/// like `ctx.db.corridor()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.corridor().on_insert(...)`.
pub struct CorridorTableHandle<'ctx> {
    imp: __sdk::TableHandle<Corridor>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `corridor`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CorridorTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CorridorTableHandle`], which mediates access to the table `corridor`.
    fn corridor(&self) -> CorridorTableHandle<'_>;
}

impl CorridorTableAccess for super::RemoteTables {
    fn corridor(&self) -> CorridorTableHandle<'_> {
        CorridorTableHandle {
            imp: self.imp.get_table::<Corridor>("corridor"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CorridorInsertCallbackId(__sdk::CallbackId);
pub struct CorridorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CorridorTableHandle<'ctx> {
    type Row = Corridor;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Corridor> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CorridorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CorridorInsertCallbackId {
        CorridorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CorridorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CorridorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CorridorDeleteCallbackId {
        CorridorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CorridorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Corridor>("corridor");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct CorridorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CorridorTableHandle<'ctx> {
    type UpdateCallbackId = CorridorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CorridorUpdateCallbackId {
        CorridorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CorridorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Corridor>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Corridor>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `corridor`,
/// which allows point queries on the field of the same name
/// via the [`CorridorIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.corridor().id().find(...)`.
pub struct CorridorIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Corridor, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CorridorTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `corridor`.
    pub fn id(&self) -> CorridorIdUnique<'ctx> {
        CorridorIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CorridorIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Corridor> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Corridor`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait corridorQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Corridor`.
    fn corridor(&self) -> __sdk::__query_builder::Table<Corridor>;
}

impl corridorQueryTableAccess for __sdk::QueryTableAccessor {
    fn corridor(&self) -> __sdk::__query_builder::Table<Corridor> {
        __sdk::__query_builder::Table::new("corridor")
    }
}
