// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::crew_type::Crew;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `crew`.
///
/// Obtain a handle from the [`CrewTableAccess::crew`] method on [`super::RemoteTables`],
/// like `ctx.db.crew()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.crew().on_insert(...)`.
pub struct CrewTableHandle<'ctx> {
    imp: __sdk::TableHandle<Crew>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `crew`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CrewTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CrewTableHandle`], which mediates access to the table `crew`.
    fn crew(&self) -> CrewTableHandle<'_>;
}

impl CrewTableAccess for super::RemoteTables {
    fn crew(&self) -> CrewTableHandle<'_> {
        CrewTableHandle {
            imp: self.imp.get_table::<Crew>("crew"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CrewInsertCallbackId(__sdk::CallbackId);
pub struct CrewDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CrewTableHandle<'ctx> {
    type Row = Crew;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Crew> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CrewInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CrewInsertCallbackId {
        CrewInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CrewInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CrewDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CrewDeleteCallbackId {
        CrewDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CrewDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Crew>("crew");
    _table.add_unique_constraint::<u64>("person_id", |row| &row.person_id);
}
pub struct CrewUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CrewTableHandle<'ctx> {
    type UpdateCallbackId = CrewUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CrewUpdateCallbackId {
        CrewUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CrewUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Crew>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Crew>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `person_id` unique index on the table `crew`,
/// which allows point queries on the field of the same name
/// via the [`CrewPersonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.crew().person_id().find(...)`.
pub struct CrewPersonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Crew, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CrewTableHandle<'ctx> {
    /// Get a handle on the `person_id` unique index on the table `crew`.
    pub fn person_id(&self) -> CrewPersonIdUnique<'ctx> {
        CrewPersonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("person_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CrewPersonIdUnique<'ctx> {
    /// Find the subscribed row whose `person_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Crew> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Crew`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait crewQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Crew`.
    fn crew(&self) -> __sdk::__query_builder::Table<Crew>;
}

impl crewQueryTableAccess for __sdk::QueryTableAccessor {
    fn crew(&self) -> __sdk::__query_builder::Table<Crew> {
        __sdk::__query_builder::Table::new("crew")
    }
}
