// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Crew {
    pub person_id: u64,
    pub department: u8,
    pub rank: u8,
    pub shift: u8,
    pub duty_station_id: u32,
    pub on_duty: bool,
}

impl __sdk::InModule for Crew {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Crew`.
///
/// Provides typed access to columns for query building.
pub struct CrewCols {
    pub person_id: __sdk::__query_builder::Col<Crew, u64>,
    pub department: __sdk::__query_builder::Col<Crew, u8>,
    pub rank: __sdk::__query_builder::Col<Crew, u8>,
    pub shift: __sdk::__query_builder::Col<Crew, u8>,
    pub duty_station_id: __sdk::__query_builder::Col<Crew, u32>,
    pub on_duty: __sdk::__query_builder::Col<Crew, bool>,
}

impl __sdk::__query_builder::HasCols for Crew {
    type Cols = CrewCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CrewCols {
            person_id: __sdk::__query_builder::Col::new(table_name, "person_id"),
            department: __sdk::__query_builder::Col::new(table_name, "department"),
            rank: __sdk::__query_builder::Col::new(table_name, "rank"),
            shift: __sdk::__query_builder::Col::new(table_name, "shift"),
            duty_station_id: __sdk::__query_builder::Col::new(table_name, "duty_station_id"),
            on_duty: __sdk::__query_builder::Col::new(table_name, "on_duty"),
        }
    }
}

/// Indexed column accessor struct for the table `Crew`.
///
/// Provides typed access to indexed columns for query building.
pub struct CrewIxCols {
    pub person_id: __sdk::__query_builder::IxCol<Crew, u64>,
}

impl __sdk::__query_builder::HasIxCols for Crew {
    type IxCols = CrewIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CrewIxCols {
            person_id: __sdk::__query_builder::IxCol::new(table_name, "person_id"),
        }
    }
}
