// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::deck_atmosphere_type::DeckAtmosphere;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `deck_atmosphere`.
///
/// Obtain a handle from the [`DeckAtmosphereTableAccess::deck_atmosphere`] method on [`super::RemoteTables`],
/// like `ctx.db.deck_atmosphere()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.deck_atmosphere().on_insert(...)`.
pub struct DeckAtmosphereTableHandle<'ctx> {
    imp: __sdk::TableHandle<DeckAtmosphere>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `deck_atmosphere`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DeckAtmosphereTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DeckAtmosphereTableHandle`], which mediates access to the table `deck_atmosphere`.
    fn deck_atmosphere(&self) -> DeckAtmosphereTableHandle<'_>;
}

impl DeckAtmosphereTableAccess for super::RemoteTables {
    fn deck_atmosphere(&self) -> DeckAtmosphereTableHandle<'_> {
        DeckAtmosphereTableHandle {
            imp: self.imp.get_table::<DeckAtmosphere>("deck_atmosphere"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DeckAtmosphereInsertCallbackId(__sdk::CallbackId);
pub struct DeckAtmosphereDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DeckAtmosphereTableHandle<'ctx> {
    type Row = DeckAtmosphere;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DeckAtmosphere> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DeckAtmosphereInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeckAtmosphereInsertCallbackId {
        DeckAtmosphereInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DeckAtmosphereInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DeckAtmosphereDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeckAtmosphereDeleteCallbackId {
        DeckAtmosphereDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DeckAtmosphereDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DeckAtmosphere>("deck_atmosphere");
    _table.add_unique_constraint::<i32>("deck", |row| &row.deck);
}
pub struct DeckAtmosphereUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DeckAtmosphereTableHandle<'ctx> {
    type UpdateCallbackId = DeckAtmosphereUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DeckAtmosphereUpdateCallbackId {
        DeckAtmosphereUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DeckAtmosphereUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DeckAtmosphere>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DeckAtmosphere>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `deck` unique index on the table `deck_atmosphere`,
/// which allows point queries on the field of the same name
/// via the [`DeckAtmosphereDeckUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.deck_atmosphere().deck().find(...)`.
pub struct DeckAtmosphereDeckUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DeckAtmosphere, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DeckAtmosphereTableHandle<'ctx> {
    /// Get a handle on the `deck` unique index on the table `deck_atmosphere`.
    pub fn deck(&self) -> DeckAtmosphereDeckUnique<'ctx> {
        DeckAtmosphereDeckUnique {
            imp: self.imp.get_unique_constraint::<i32>("deck"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DeckAtmosphereDeckUnique<'ctx> {
    /// Find the subscribed row whose `deck` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<DeckAtmosphere> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DeckAtmosphere`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait deck_atmosphereQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DeckAtmosphere`.
    fn deck_atmosphere(&self) -> __sdk::__query_builder::Table<DeckAtmosphere>;
}

impl deck_atmosphereQueryTableAccess for __sdk::QueryTableAccessor {
    fn deck_atmosphere(&self) -> __sdk::__query_builder::Table<DeckAtmosphere> {
        __sdk::__query_builder::Table::new("deck_atmosphere")
    }
}
