// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DeckAtmosphere {
    pub deck: i32,
    pub oxygen: f32,
    pub co_2: f32,
    pub humidity: f32,
    pub temperature: f32,
    pub pressure: f32,
}

impl __sdk::InModule for DeckAtmosphere {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DeckAtmosphere`.
///
/// Provides typed access to columns for query building.
pub struct DeckAtmosphereCols {
    pub deck: __sdk::__query_builder::Col<DeckAtmosphere, i32>,
    pub oxygen: __sdk::__query_builder::Col<DeckAtmosphere, f32>,
    pub co2: __sdk::__query_builder::Col<DeckAtmosphere, f32>,
    pub humidity: __sdk::__query_builder::Col<DeckAtmosphere, f32>,
    pub temperature: __sdk::__query_builder::Col<DeckAtmosphere, f32>,
    pub pressure: __sdk::__query_builder::Col<DeckAtmosphere, f32>,
}

impl __sdk::__query_builder::HasCols for DeckAtmosphere {
    type Cols = DeckAtmosphereCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeckAtmosphereCols {
            deck: __sdk::__query_builder::Col::new(table_name, "deck"),
            oxygen: __sdk::__query_builder::Col::new(table_name, "oxygen"),
            co2: __sdk::__query_builder::Col::new(table_name, "co2"),
            humidity: __sdk::__query_builder::Col::new(table_name, "humidity"),
            temperature: __sdk::__query_builder::Col::new(table_name, "temperature"),
            pressure: __sdk::__query_builder::Col::new(table_name, "pressure"),
        }
    }
}

/// Indexed column accessor struct for the table `DeckAtmosphere`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeckAtmosphereIxCols {
    pub deck: __sdk::__query_builder::IxCol<DeckAtmosphere, i32>,
}

impl __sdk::__query_builder::HasIxCols for DeckAtmosphere {
    type IxCols = DeckAtmosphereIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeckAtmosphereIxCols {
            deck: __sdk::__query_builder::IxCol::new(table_name, "deck"),
        }
    }
}
