// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::door_type::Door;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `door`.
///
/// Obtain a handle from the [`DoorTableAccess::door`] method on [`super::RemoteTables`],
/// like `ctx.db.door()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.door().on_insert(...)`.
pub struct DoorTableHandle<'ctx> {
    imp: __sdk::TableHandle<Door>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `door`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DoorTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DoorTableHandle`], which mediates access to the table `door`.
    fn door(&self) -> DoorTableHandle<'_>;
}

impl DoorTableAccess for super::RemoteTables {
    fn door(&self) -> DoorTableHandle<'_> {
        DoorTableHandle {
            imp: self.imp.get_table::<Door>("door"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DoorInsertCallbackId(__sdk::CallbackId);
pub struct DoorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DoorTableHandle<'ctx> {
    type Row = Door;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Door> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DoorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DoorInsertCallbackId {
        DoorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DoorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DoorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DoorDeleteCallbackId {
        DoorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DoorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Door>("door");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct DoorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DoorTableHandle<'ctx> {
    type UpdateCallbackId = DoorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DoorUpdateCallbackId {
        DoorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DoorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Door>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Door>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `door`,
/// which allows point queries on the field of the same name
/// via the [`DoorIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.door().id().find(...)`.
pub struct DoorIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Door, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DoorTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `door`.
    pub fn id(&self) -> DoorIdUnique<'ctx> {
        DoorIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DoorIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Door> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Door`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait doorQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Door`.
    fn door(&self) -> __sdk::__query_builder::Table<Door>;
}

impl doorQueryTableAccess for __sdk::QueryTableAccessor {
    fn door(&self) -> __sdk::__query_builder::Table<Door> {
        __sdk::__query_builder::Table::new("door")
    }
}
