// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Door {
    pub id: u64,
    pub room_a: u32,
    pub room_b: u32,
    pub wall_a: u8,
    pub wall_b: u8,
    pub position_along_wall: f32,
    pub width: f32,
    pub access_level: u8,
    pub door_x: f32,
    pub door_y: f32,
}

impl __sdk::InModule for Door {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Door`.
///
/// Provides typed access to columns for query building.
pub struct DoorCols {
    pub id: __sdk::__query_builder::Col<Door, u64>,
    pub room_a: __sdk::__query_builder::Col<Door, u32>,
    pub room_b: __sdk::__query_builder::Col<Door, u32>,
    pub wall_a: __sdk::__query_builder::Col<Door, u8>,
    pub wall_b: __sdk::__query_builder::Col<Door, u8>,
    pub position_along_wall: __sdk::__query_builder::Col<Door, f32>,
    pub width: __sdk::__query_builder::Col<Door, f32>,
    pub access_level: __sdk::__query_builder::Col<Door, u8>,
    pub door_x: __sdk::__query_builder::Col<Door, f32>,
    pub door_y: __sdk::__query_builder::Col<Door, f32>,
}

impl __sdk::__query_builder::HasCols for Door {
    type Cols = DoorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DoorCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            room_a: __sdk::__query_builder::Col::new(table_name, "room_a"),
            room_b: __sdk::__query_builder::Col::new(table_name, "room_b"),
            wall_a: __sdk::__query_builder::Col::new(table_name, "wall_a"),
            wall_b: __sdk::__query_builder::Col::new(table_name, "wall_b"),
            position_along_wall: __sdk::__query_builder::Col::new(
                table_name,
                "position_along_wall",
            ),
            width: __sdk::__query_builder::Col::new(table_name, "width"),
            access_level: __sdk::__query_builder::Col::new(table_name, "access_level"),
            door_x: __sdk::__query_builder::Col::new(table_name, "door_x"),
            door_y: __sdk::__query_builder::Col::new(table_name, "door_y"),
        }
    }
}

/// Indexed column accessor struct for the table `Door`.
///
/// Provides typed access to indexed columns for query building.
pub struct DoorIxCols {
    pub id: __sdk::__query_builder::IxCol<Door, u64>,
}

impl __sdk::__query_builder::HasIxCols for Door {
    type IxCols = DoorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DoorIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
