// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Event {
    pub id: u64,
    pub event_type: u8,
    pub room_id: u32,
    pub started_at: f64,
    pub duration: f32,
    pub state: u8,
    pub responders_needed: u8,
    pub responders_assigned: u8,
    pub severity: f32,
}

impl __sdk::InModule for Event {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Event`.
///
/// Provides typed access to columns for query building.
pub struct EventCols {
    pub id: __sdk::__query_builder::Col<Event, u64>,
    pub event_type: __sdk::__query_builder::Col<Event, u8>,
    pub room_id: __sdk::__query_builder::Col<Event, u32>,
    pub started_at: __sdk::__query_builder::Col<Event, f64>,
    pub duration: __sdk::__query_builder::Col<Event, f32>,
    pub state: __sdk::__query_builder::Col<Event, u8>,
    pub responders_needed: __sdk::__query_builder::Col<Event, u8>,
    pub responders_assigned: __sdk::__query_builder::Col<Event, u8>,
    pub severity: __sdk::__query_builder::Col<Event, f32>,
}

impl __sdk::__query_builder::HasCols for Event {
    type Cols = EventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            event_type: __sdk::__query_builder::Col::new(table_name, "event_type"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            duration: __sdk::__query_builder::Col::new(table_name, "duration"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            responders_needed: __sdk::__query_builder::Col::new(table_name, "responders_needed"),
            responders_assigned: __sdk::__query_builder::Col::new(
                table_name,
                "responders_assigned",
            ),
            severity: __sdk::__query_builder::Col::new(table_name, "severity"),
        }
    }
}

/// Indexed column accessor struct for the table `Event`.
///
/// Provides typed access to indexed columns for query building.
pub struct EventIxCols {
    pub id: __sdk::__query_builder::IxCol<Event, u64>,
}

impl __sdk::__query_builder::HasIxCols for Event {
    type IxCols = EventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
