// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GraphEdge {
    pub id: u64,
    pub from_node: u64,
    pub to_node: u64,
    pub edge_type: u8,
    pub weight: f32,
    pub bidirectional: bool,
}

impl __sdk::InModule for GraphEdge {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GraphEdge`.
///
/// Provides typed access to columns for query building.
pub struct GraphEdgeCols {
    pub id: __sdk::__query_builder::Col<GraphEdge, u64>,
    pub from_node: __sdk::__query_builder::Col<GraphEdge, u64>,
    pub to_node: __sdk::__query_builder::Col<GraphEdge, u64>,
    pub edge_type: __sdk::__query_builder::Col<GraphEdge, u8>,
    pub weight: __sdk::__query_builder::Col<GraphEdge, f32>,
    pub bidirectional: __sdk::__query_builder::Col<GraphEdge, bool>,
}

impl __sdk::__query_builder::HasCols for GraphEdge {
    type Cols = GraphEdgeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GraphEdgeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            from_node: __sdk::__query_builder::Col::new(table_name, "from_node"),
            to_node: __sdk::__query_builder::Col::new(table_name, "to_node"),
            edge_type: __sdk::__query_builder::Col::new(table_name, "edge_type"),
            weight: __sdk::__query_builder::Col::new(table_name, "weight"),
            bidirectional: __sdk::__query_builder::Col::new(table_name, "bidirectional"),
        }
    }
}

/// Indexed column accessor struct for the table `GraphEdge`.
///
/// Provides typed access to indexed columns for query building.
pub struct GraphEdgeIxCols {
    pub id: __sdk::__query_builder::IxCol<GraphEdge, u64>,
}

impl __sdk::__query_builder::HasIxCols for GraphEdge {
    type IxCols = GraphEdgeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GraphEdgeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
