// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::graph_node_type::GraphNode;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `graph_node`.
///
/// Obtain a handle from the [`GraphNodeTableAccess::graph_node`] method on [`super::RemoteTables`],
/// like `ctx.db.graph_node()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.graph_node().on_insert(...)`.
pub struct GraphNodeTableHandle<'ctx> {
    imp: __sdk::TableHandle<GraphNode>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `graph_node`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GraphNodeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GraphNodeTableHandle`], which mediates access to the table `graph_node`.
    fn graph_node(&self) -> GraphNodeTableHandle<'_>;
}

impl GraphNodeTableAccess for super::RemoteTables {
    fn graph_node(&self) -> GraphNodeTableHandle<'_> {
        GraphNodeTableHandle {
            imp: self.imp.get_table::<GraphNode>("graph_node"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GraphNodeInsertCallbackId(__sdk::CallbackId);
pub struct GraphNodeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GraphNodeTableHandle<'ctx> {
    type Row = GraphNode;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GraphNode> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GraphNodeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GraphNodeInsertCallbackId {
        GraphNodeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GraphNodeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GraphNodeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GraphNodeDeleteCallbackId {
        GraphNodeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GraphNodeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GraphNode>("graph_node");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct GraphNodeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GraphNodeTableHandle<'ctx> {
    type UpdateCallbackId = GraphNodeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GraphNodeUpdateCallbackId {
        GraphNodeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GraphNodeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GraphNode>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GraphNode>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `graph_node`,
/// which allows point queries on the field of the same name
/// via the [`GraphNodeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.graph_node().id().find(...)`.
pub struct GraphNodeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GraphNode, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GraphNodeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `graph_node`.
    pub fn id(&self) -> GraphNodeIdUnique<'ctx> {
        GraphNodeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GraphNodeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GraphNode> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GraphNode`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait graph_nodeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GraphNode`.
    fn graph_node(&self) -> __sdk::__query_builder::Table<GraphNode>;
}

impl graph_nodeQueryTableAccess for __sdk::QueryTableAccessor {
    fn graph_node(&self) -> __sdk::__query_builder::Table<GraphNode> {
        __sdk::__query_builder::Table::new("graph_node")
    }
}
