// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::graph_edge_type::GraphEdge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `graph_edge`.
///
/// Obtain a handle from the [`GraphEdgeTableAccess::graph_edge`] method on [`super::RemoteTables`],
/// like `ctx.db.graph_edge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.graph_edge().on_insert(...)`.
pub struct GraphEdgeTableHandle<'ctx> {
    imp: __sdk::TableHandle<GraphEdge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `graph_edge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GraphEdgeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GraphEdgeTableHandle`], which mediates access to the table `graph_edge`.
    fn graph_edge(&self) -> GraphEdgeTableHandle<'_>;
}

impl GraphEdgeTableAccess for super::RemoteTables {
    fn graph_edge(&self) -> GraphEdgeTableHandle<'_> {
        GraphEdgeTableHandle {
            imp: self.imp.get_table::<GraphEdge>("graph_edge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GraphEdgeInsertCallbackId(__sdk::CallbackId);
pub struct GraphEdgeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GraphEdgeTableHandle<'ctx> {
    type Row = GraphEdge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GraphEdge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GraphEdgeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GraphEdgeInsertCallbackId {
        GraphEdgeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GraphEdgeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GraphEdgeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GraphEdgeDeleteCallbackId {
        GraphEdgeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GraphEdgeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GraphEdge>("graph_edge");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct GraphEdgeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GraphEdgeTableHandle<'ctx> {
    type UpdateCallbackId = GraphEdgeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GraphEdgeUpdateCallbackId {
        GraphEdgeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GraphEdgeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GraphEdge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GraphEdge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `graph_edge`,
/// which allows point queries on the field of the same name
/// via the [`GraphEdgeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.graph_edge().id().find(...)`.
pub struct GraphEdgeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GraphEdge, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GraphEdgeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `graph_edge`.
    pub fn id(&self) -> GraphEdgeIdUnique<'ctx> {
        GraphEdgeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GraphEdgeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GraphEdge> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GraphEdge`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait graph_edgeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GraphEdge`.
    fn graph_edge(&self) -> __sdk::__query_builder::Table<GraphEdge>;
}

impl graph_edgeQueryTableAccess for __sdk::QueryTableAccessor {
    fn graph_edge(&self) -> __sdk::__query_builder::Table<GraphEdge> {
        __sdk::__query_builder::Table::new("graph_edge")
    }
}
