// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GraphNode {
    pub id: u64,
    pub node_type: u8,
    pub name: String,
    pub function: u8,
    pub capacity: u32,
    pub required_area: f32,
    pub deck_preference: i32,
    pub group: u8,
}

impl __sdk::InModule for GraphNode {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GraphNode`.
///
/// Provides typed access to columns for query building.
pub struct GraphNodeCols {
    pub id: __sdk::__query_builder::Col<GraphNode, u64>,
    pub node_type: __sdk::__query_builder::Col<GraphNode, u8>,
    pub name: __sdk::__query_builder::Col<GraphNode, String>,
    pub function: __sdk::__query_builder::Col<GraphNode, u8>,
    pub capacity: __sdk::__query_builder::Col<GraphNode, u32>,
    pub required_area: __sdk::__query_builder::Col<GraphNode, f32>,
    pub deck_preference: __sdk::__query_builder::Col<GraphNode, i32>,
    pub group: __sdk::__query_builder::Col<GraphNode, u8>,
}

impl __sdk::__query_builder::HasCols for GraphNode {
    type Cols = GraphNodeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GraphNodeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            node_type: __sdk::__query_builder::Col::new(table_name, "node_type"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            function: __sdk::__query_builder::Col::new(table_name, "function"),
            capacity: __sdk::__query_builder::Col::new(table_name, "capacity"),
            required_area: __sdk::__query_builder::Col::new(table_name, "required_area"),
            deck_preference: __sdk::__query_builder::Col::new(table_name, "deck_preference"),
            group: __sdk::__query_builder::Col::new(table_name, "group"),
        }
    }
}

/// Indexed column accessor struct for the table `GraphNode`.
///
/// Provides typed access to indexed columns for query building.
pub struct GraphNodeIxCols {
    pub id: __sdk::__query_builder::IxCol<GraphNode, u64>,
}

impl __sdk::__query_builder::HasIxCols for GraphNode {
    type IxCols = GraphNodeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GraphNodeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
