// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::in_conversation_type::InConversation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `in_conversation`.
///
/// Obtain a handle from the [`InConversationTableAccess::in_conversation`] method on [`super::RemoteTables`],
/// like `ctx.db.in_conversation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.in_conversation().on_insert(...)`.
pub struct InConversationTableHandle<'ctx> {
    imp: __sdk::TableHandle<InConversation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `in_conversation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InConversationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InConversationTableHandle`], which mediates access to the table `in_conversation`.
    fn in_conversation(&self) -> InConversationTableHandle<'_>;
}

impl InConversationTableAccess for super::RemoteTables {
    fn in_conversation(&self) -> InConversationTableHandle<'_> {
        InConversationTableHandle {
            imp: self.imp.get_table::<InConversation>("in_conversation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InConversationInsertCallbackId(__sdk::CallbackId);
pub struct InConversationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InConversationTableHandle<'ctx> {
    type Row = InConversation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InConversation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InConversationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InConversationInsertCallbackId {
        InConversationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InConversationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InConversationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InConversationDeleteCallbackId {
        InConversationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InConversationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InConversation>("in_conversation");
    _table.add_unique_constraint::<u64>("person_id", |row| &row.person_id);
}
pub struct InConversationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InConversationTableHandle<'ctx> {
    type UpdateCallbackId = InConversationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InConversationUpdateCallbackId {
        InConversationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InConversationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<InConversation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InConversation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `person_id` unique index on the table `in_conversation`,
/// which allows point queries on the field of the same name
/// via the [`InConversationPersonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.in_conversation().person_id().find(...)`.
pub struct InConversationPersonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InConversation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InConversationTableHandle<'ctx> {
    /// Get a handle on the `person_id` unique index on the table `in_conversation`.
    pub fn person_id(&self) -> InConversationPersonIdUnique<'ctx> {
        InConversationPersonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("person_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InConversationPersonIdUnique<'ctx> {
    /// Find the subscribed row whose `person_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<InConversation> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InConversation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait in_conversationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InConversation`.
    fn in_conversation(&self) -> __sdk::__query_builder::Table<InConversation>;
}

impl in_conversationQueryTableAccess for __sdk::QueryTableAccessor {
    fn in_conversation(&self) -> __sdk::__query_builder::Table<InConversation> {
        __sdk::__query_builder::Table::new("in_conversation")
    }
}
