// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InConversation {
    pub person_id: u64,
    pub conversation_id: u64,
}

impl __sdk::InModule for InConversation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InConversation`.
///
/// Provides typed access to columns for query building.
pub struct InConversationCols {
    pub person_id: __sdk::__query_builder::Col<InConversation, u64>,
    pub conversation_id: __sdk::__query_builder::Col<InConversation, u64>,
}

impl __sdk::__query_builder::HasCols for InConversation {
    type Cols = InConversationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InConversationCols {
            person_id: __sdk::__query_builder::Col::new(table_name, "person_id"),
            conversation_id: __sdk::__query_builder::Col::new(table_name, "conversation_id"),
        }
    }
}

/// Indexed column accessor struct for the table `InConversation`.
///
/// Provides typed access to indexed columns for query building.
pub struct InConversationIxCols {
    pub person_id: __sdk::__query_builder::IxCol<InConversation, u64>,
}

impl __sdk::__query_builder::HasIxCols for InConversation {
    type IxCols = InConversationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InConversationIxCols {
            person_id: __sdk::__query_builder::IxCol::new(table_name, "person_id"),
        }
    }
}
