// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::infra_edge_type::InfraEdge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `infra_edge`.
///
/// Obtain a handle from the [`InfraEdgeTableAccess::infra_edge`] method on [`super::RemoteTables`],
/// like `ctx.db.infra_edge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.infra_edge().on_insert(...)`.
pub struct InfraEdgeTableHandle<'ctx> {
    imp: __sdk::TableHandle<InfraEdge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `infra_edge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InfraEdgeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InfraEdgeTableHandle`], which mediates access to the table `infra_edge`.
    fn infra_edge(&self) -> InfraEdgeTableHandle<'_>;
}

impl InfraEdgeTableAccess for super::RemoteTables {
    fn infra_edge(&self) -> InfraEdgeTableHandle<'_> {
        InfraEdgeTableHandle {
            imp: self.imp.get_table::<InfraEdge>("infra_edge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InfraEdgeInsertCallbackId(__sdk::CallbackId);
pub struct InfraEdgeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InfraEdgeTableHandle<'ctx> {
    type Row = InfraEdge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InfraEdge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InfraEdgeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InfraEdgeInsertCallbackId {
        InfraEdgeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InfraEdgeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InfraEdgeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InfraEdgeDeleteCallbackId {
        InfraEdgeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InfraEdgeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InfraEdge>("infra_edge");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct InfraEdgeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InfraEdgeTableHandle<'ctx> {
    type UpdateCallbackId = InfraEdgeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InfraEdgeUpdateCallbackId {
        InfraEdgeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InfraEdgeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<InfraEdge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InfraEdge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `infra_edge`,
/// which allows point queries on the field of the same name
/// via the [`InfraEdgeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.infra_edge().id().find(...)`.
pub struct InfraEdgeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InfraEdge, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InfraEdgeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `infra_edge`.
    pub fn id(&self) -> InfraEdgeIdUnique<'ctx> {
        InfraEdgeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InfraEdgeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<InfraEdge> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InfraEdge`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait infra_edgeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InfraEdge`.
    fn infra_edge(&self) -> __sdk::__query_builder::Table<InfraEdge>;
}

impl infra_edgeQueryTableAccess for __sdk::QueryTableAccessor {
    fn infra_edge(&self) -> __sdk::__query_builder::Table<InfraEdge> {
        __sdk::__query_builder::Table::new("infra_edge")
    }
}
