// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InfraEdge {
    pub id: u64,
    pub graph_edge_id: u64,
    pub edge_type: u8,
    pub corridor_id: u64,
    pub capacity: f32,
    pub current_flow: f32,
    pub health: f32,
}

impl __sdk::InModule for InfraEdge {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InfraEdge`.
///
/// Provides typed access to columns for query building.
pub struct InfraEdgeCols {
    pub id: __sdk::__query_builder::Col<InfraEdge, u64>,
    pub graph_edge_id: __sdk::__query_builder::Col<InfraEdge, u64>,
    pub edge_type: __sdk::__query_builder::Col<InfraEdge, u8>,
    pub corridor_id: __sdk::__query_builder::Col<InfraEdge, u64>,
    pub capacity: __sdk::__query_builder::Col<InfraEdge, f32>,
    pub current_flow: __sdk::__query_builder::Col<InfraEdge, f32>,
    pub health: __sdk::__query_builder::Col<InfraEdge, f32>,
}

impl __sdk::__query_builder::HasCols for InfraEdge {
    type Cols = InfraEdgeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InfraEdgeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            graph_edge_id: __sdk::__query_builder::Col::new(table_name, "graph_edge_id"),
            edge_type: __sdk::__query_builder::Col::new(table_name, "edge_type"),
            corridor_id: __sdk::__query_builder::Col::new(table_name, "corridor_id"),
            capacity: __sdk::__query_builder::Col::new(table_name, "capacity"),
            current_flow: __sdk::__query_builder::Col::new(table_name, "current_flow"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
        }
    }
}

/// Indexed column accessor struct for the table `InfraEdge`.
///
/// Provides typed access to indexed columns for query building.
pub struct InfraEdgeIxCols {
    pub id: __sdk::__query_builder::IxCol<InfraEdge, u64>,
}

impl __sdk::__query_builder::HasIxCols for InfraEdge {
    type IxCols = InfraEdgeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InfraEdgeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
