// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InitShipArgs {
    pub name: String,
    pub deck_count: u32,
    pub crew_count: u32,
    pub passenger_count: u32,
}

impl From<InitShipArgs> for super::Reducer {
    fn from(args: InitShipArgs) -> Self {
        Self::InitShip {
            name: args.name,
            deck_count: args.deck_count,
            crew_count: args.crew_count,
            passenger_count: args.passenger_count,
        }
    }
}

impl __sdk::InModule for InitShipArgs {
    type Module = super::RemoteModule;
}

pub struct InitShipCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `init_ship`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait init_ship {
    /// Request that the remote module invoke the reducer `init_ship` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_init_ship`] callbacks.
    fn init_ship(
        &self,
        name: String,
        deck_count: u32,
        crew_count: u32,
        passenger_count: u32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `init_ship`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`InitShipCallbackId`] can be passed to [`Self::remove_on_init_ship`]
    /// to cancel the callback.
    fn on_init_ship(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &u32, &u32, &u32) + Send + 'static,
    ) -> InitShipCallbackId;
    /// Cancel a callback previously registered by [`Self::on_init_ship`],
    /// causing it not to run in the future.
    fn remove_on_init_ship(&self, callback: InitShipCallbackId);
}

impl init_ship for super::RemoteReducers {
    fn init_ship(
        &self,
        name: String,
        deck_count: u32,
        crew_count: u32,
        passenger_count: u32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "init_ship",
            InitShipArgs {
                name,
                deck_count,
                crew_count,
                passenger_count,
            },
        )
    }
    fn on_init_ship(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &u32, &u32, &u32)
            + Send
            + 'static,
    ) -> InitShipCallbackId {
        InitShipCallbackId(self.imp.on_reducer(
            "init_ship",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::InitShip {
                                    name,
                                    deck_count,
                                    crew_count,
                                    passenger_count,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name, deck_count, crew_count, passenger_count)
            }),
        ))
    }
    fn remove_on_init_ship(&self, callback: InitShipCallbackId) {
        self.imp.remove_on_reducer("init_ship", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `init_ship`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_init_ship {
    /// Set the call-reducer flags for the reducer `init_ship` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn init_ship(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_init_ship for super::SetReducerFlags {
    fn init_ship(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("init_ship", flags);
    }
}
