// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.12.0 (commit 92fdc93b9507ac89061cafb4f4909b3a1162e59d).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod activity_table;
pub mod activity_type;
pub mod client_connected_reducer;
pub mod client_disconnected_reducer;
pub mod connected_player_table;
pub mod connected_player_type;
pub mod conversation_table;
pub mod conversation_type;
pub mod corridor_table;
pub mod corridor_type;
pub mod crew_table;
pub mod crew_type;
pub mod deck_atmosphere_table;
pub mod deck_atmosphere_type;
pub mod door_table;
pub mod door_type;
pub mod event_table;
pub mod event_type;
pub mod graph_edge_table;
pub mod graph_edge_type;
pub mod graph_node_table;
pub mod graph_node_type;
pub mod in_conversation_table;
pub mod in_conversation_type;
pub mod infra_edge_table;
pub mod infra_edge_type;
pub mod init_ship_reducer;
pub mod maintenance_task_table;
pub mod maintenance_task_type;
pub mod movement_table;
pub mod movement_type;
pub mod needs_table;
pub mod needs_type;
pub mod passenger_table;
pub mod passenger_type;
pub mod person_table;
pub mod person_type;
pub mod personality_table;
pub mod personality_type;
pub mod player_action_reducer;
pub mod player_interact_reducer;
pub mod player_join_reducer;
pub mod player_move_reducer;
pub mod player_use_elevator_reducer;
pub mod player_use_ladder_reducer;
pub mod position_table;
pub mod position_type;
pub mod relationship_table;
pub mod relationship_type;
pub mod room_table;
pub mod room_type;
pub mod set_paused_reducer;
pub mod set_time_scale_reducer;
pub mod ship_config_table;
pub mod ship_config_type;
pub mod ship_resources_table;
pub mod ship_resources_type;
pub mod ship_system_table;
pub mod ship_system_type;
pub mod skills_table;
pub mod skills_type;
pub mod subsystem_table;
pub mod subsystem_type;
pub mod system_component_table;
pub mod system_component_type;
pub mod tick_reducer;
pub mod vertical_shaft_table;
pub mod vertical_shaft_type;

pub use activity_table::*;
pub use activity_type::Activity;
pub use client_connected_reducer::{
    client_connected, set_flags_for_client_connected, ClientConnectedCallbackId,
};
pub use client_disconnected_reducer::{
    client_disconnected, set_flags_for_client_disconnected, ClientDisconnectedCallbackId,
};
pub use connected_player_table::*;
pub use connected_player_type::ConnectedPlayer;
pub use conversation_table::*;
pub use conversation_type::Conversation;
pub use corridor_table::*;
pub use corridor_type::Corridor;
pub use crew_table::*;
pub use crew_type::Crew;
pub use deck_atmosphere_table::*;
pub use deck_atmosphere_type::DeckAtmosphere;
pub use door_table::*;
pub use door_type::Door;
pub use event_table::*;
pub use event_type::Event;
pub use graph_edge_table::*;
pub use graph_edge_type::GraphEdge;
pub use graph_node_table::*;
pub use graph_node_type::GraphNode;
pub use in_conversation_table::*;
pub use in_conversation_type::InConversation;
pub use infra_edge_table::*;
pub use infra_edge_type::InfraEdge;
pub use init_ship_reducer::{init_ship, set_flags_for_init_ship, InitShipCallbackId};
pub use maintenance_task_table::*;
pub use maintenance_task_type::MaintenanceTask;
pub use movement_table::*;
pub use movement_type::Movement;
pub use needs_table::*;
pub use needs_type::Needs;
pub use passenger_table::*;
pub use passenger_type::Passenger;
pub use person_table::*;
pub use person_type::Person;
pub use personality_table::*;
pub use personality_type::Personality;
pub use player_action_reducer::{
    player_action, set_flags_for_player_action, PlayerActionCallbackId,
};
pub use player_interact_reducer::{
    player_interact, set_flags_for_player_interact, PlayerInteractCallbackId,
};
pub use player_join_reducer::{player_join, set_flags_for_player_join, PlayerJoinCallbackId};
pub use player_move_reducer::{player_move, set_flags_for_player_move, PlayerMoveCallbackId};
pub use player_use_elevator_reducer::{
    player_use_elevator, set_flags_for_player_use_elevator, PlayerUseElevatorCallbackId,
};
pub use player_use_ladder_reducer::{
    player_use_ladder, set_flags_for_player_use_ladder, PlayerUseLadderCallbackId,
};
pub use position_table::*;
pub use position_type::Position;
pub use relationship_table::*;
pub use relationship_type::Relationship;
pub use room_table::*;
pub use room_type::Room;
pub use set_paused_reducer::{set_flags_for_set_paused, set_paused, SetPausedCallbackId};
pub use set_time_scale_reducer::{
    set_flags_for_set_time_scale, set_time_scale, SetTimeScaleCallbackId,
};
pub use ship_config_table::*;
pub use ship_config_type::ShipConfig;
pub use ship_resources_table::*;
pub use ship_resources_type::ShipResources;
pub use ship_system_table::*;
pub use ship_system_type::ShipSystem;
pub use skills_table::*;
pub use skills_type::Skills;
pub use subsystem_table::*;
pub use subsystem_type::Subsystem;
pub use system_component_table::*;
pub use system_component_type::SystemComponent;
pub use tick_reducer::{set_flags_for_tick, tick, TickCallbackId};
pub use vertical_shaft_table::*;
pub use vertical_shaft_type::VerticalShaft;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ClientConnected,
    ClientDisconnected,
    InitShip {
        name: String,
        deck_count: u32,
        crew_count: u32,
        passenger_count: u32,
    },
    PlayerAction {
        action: u8,
    },
    PlayerInteract {
        target_person_id: u64,
    },
    PlayerJoin {
        given_name: String,
        family_name: String,
        is_crew: bool,
    },
    PlayerMove {
        dx: f32,
        dy: f32,
    },
    PlayerUseElevator {
        target_deck: i32,
    },
    PlayerUseLadder {
        direction: i32,
    },
    SetPaused {
        paused: bool,
    },
    SetTimeScale {
        scale: f32,
    },
    Tick {
        delta_seconds: f32,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ClientConnected => "client_connected",
            Reducer::ClientDisconnected => "client_disconnected",
            Reducer::InitShip { .. } => "init_ship",
            Reducer::PlayerAction { .. } => "player_action",
            Reducer::PlayerInteract { .. } => "player_interact",
            Reducer::PlayerJoin { .. } => "player_join",
            Reducer::PlayerMove { .. } => "player_move",
            Reducer::PlayerUseElevator { .. } => "player_use_elevator",
            Reducer::PlayerUseLadder { .. } => "player_use_ladder",
            Reducer::SetPaused { .. } => "set_paused",
            Reducer::SetTimeScale { .. } => "set_time_scale",
            Reducer::Tick { .. } => "tick",
            _ => unreachable!(),
        }
    }
}
impl TryFrom<__ws::ReducerCallInfo<__ws::BsatnFormat>> for Reducer {
    type Error = __sdk::Error;
    fn try_from(value: __ws::ReducerCallInfo<__ws::BsatnFormat>) -> __sdk::Result<Self> {
        match &value.reducer_name[..] {
            "client_connected" => Ok(__sdk::parse_reducer_args::<
                client_connected_reducer::ClientConnectedArgs,
            >("client_connected", &value.args)?
            .into()),
            "client_disconnected" => Ok(__sdk::parse_reducer_args::<
                client_disconnected_reducer::ClientDisconnectedArgs,
            >("client_disconnected", &value.args)?
            .into()),
            "init_ship" => Ok(
                __sdk::parse_reducer_args::<init_ship_reducer::InitShipArgs>(
                    "init_ship",
                    &value.args,
                )?
                .into(),
            ),
            "player_action" => Ok(__sdk::parse_reducer_args::<
                player_action_reducer::PlayerActionArgs,
            >("player_action", &value.args)?
            .into()),
            "player_interact" => Ok(__sdk::parse_reducer_args::<
                player_interact_reducer::PlayerInteractArgs,
            >("player_interact", &value.args)?
            .into()),
            "player_join" => Ok(
                __sdk::parse_reducer_args::<player_join_reducer::PlayerJoinArgs>(
                    "player_join",
                    &value.args,
                )?
                .into(),
            ),
            "player_move" => Ok(
                __sdk::parse_reducer_args::<player_move_reducer::PlayerMoveArgs>(
                    "player_move",
                    &value.args,
                )?
                .into(),
            ),
            "player_use_elevator" => Ok(__sdk::parse_reducer_args::<
                player_use_elevator_reducer::PlayerUseElevatorArgs,
            >("player_use_elevator", &value.args)?
            .into()),
            "player_use_ladder" => Ok(__sdk::parse_reducer_args::<
                player_use_ladder_reducer::PlayerUseLadderArgs,
            >("player_use_ladder", &value.args)?
            .into()),
            "set_paused" => Ok(
                __sdk::parse_reducer_args::<set_paused_reducer::SetPausedArgs>(
                    "set_paused",
                    &value.args,
                )?
                .into(),
            ),
            "set_time_scale" => Ok(__sdk::parse_reducer_args::<
                set_time_scale_reducer::SetTimeScaleArgs,
            >("set_time_scale", &value.args)?
            .into()),
            "tick" => Ok(
                __sdk::parse_reducer_args::<tick_reducer::TickArgs>("tick", &value.args)?.into(),
            ),
            unknown => {
                Err(
                    __sdk::InternalError::unknown_name("reducer", unknown, "ReducerCallInfo")
                        .into(),
                )
            }
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    activity: __sdk::TableUpdate<Activity>,
    connected_player: __sdk::TableUpdate<ConnectedPlayer>,
    conversation: __sdk::TableUpdate<Conversation>,
    corridor: __sdk::TableUpdate<Corridor>,
    crew: __sdk::TableUpdate<Crew>,
    deck_atmosphere: __sdk::TableUpdate<DeckAtmosphere>,
    door: __sdk::TableUpdate<Door>,
    event: __sdk::TableUpdate<Event>,
    graph_edge: __sdk::TableUpdate<GraphEdge>,
    graph_node: __sdk::TableUpdate<GraphNode>,
    in_conversation: __sdk::TableUpdate<InConversation>,
    infra_edge: __sdk::TableUpdate<InfraEdge>,
    maintenance_task: __sdk::TableUpdate<MaintenanceTask>,
    movement: __sdk::TableUpdate<Movement>,
    needs: __sdk::TableUpdate<Needs>,
    passenger: __sdk::TableUpdate<Passenger>,
    person: __sdk::TableUpdate<Person>,
    personality: __sdk::TableUpdate<Personality>,
    position: __sdk::TableUpdate<Position>,
    relationship: __sdk::TableUpdate<Relationship>,
    room: __sdk::TableUpdate<Room>,
    ship_config: __sdk::TableUpdate<ShipConfig>,
    ship_resources: __sdk::TableUpdate<ShipResources>,
    ship_system: __sdk::TableUpdate<ShipSystem>,
    skills: __sdk::TableUpdate<Skills>,
    subsystem: __sdk::TableUpdate<Subsystem>,
    system_component: __sdk::TableUpdate<SystemComponent>,
    vertical_shaft: __sdk::TableUpdate<VerticalShaft>,
}

impl TryFrom<__ws::DatabaseUpdate<__ws::BsatnFormat>> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::DatabaseUpdate<__ws::BsatnFormat>) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in raw.tables {
            match &table_update.table_name[..] {
                "activity" => db_update
                    .activity
                    .append(activity_table::parse_table_update(table_update)?),
                "connected_player" => db_update
                    .connected_player
                    .append(connected_player_table::parse_table_update(table_update)?),
                "conversation" => db_update
                    .conversation
                    .append(conversation_table::parse_table_update(table_update)?),
                "corridor" => db_update
                    .corridor
                    .append(corridor_table::parse_table_update(table_update)?),
                "crew" => db_update
                    .crew
                    .append(crew_table::parse_table_update(table_update)?),
                "deck_atmosphere" => db_update
                    .deck_atmosphere
                    .append(deck_atmosphere_table::parse_table_update(table_update)?),
                "door" => db_update
                    .door
                    .append(door_table::parse_table_update(table_update)?),
                "event" => db_update
                    .event
                    .append(event_table::parse_table_update(table_update)?),
                "graph_edge" => db_update
                    .graph_edge
                    .append(graph_edge_table::parse_table_update(table_update)?),
                "graph_node" => db_update
                    .graph_node
                    .append(graph_node_table::parse_table_update(table_update)?),
                "in_conversation" => db_update
                    .in_conversation
                    .append(in_conversation_table::parse_table_update(table_update)?),
                "infra_edge" => db_update
                    .infra_edge
                    .append(infra_edge_table::parse_table_update(table_update)?),
                "maintenance_task" => db_update
                    .maintenance_task
                    .append(maintenance_task_table::parse_table_update(table_update)?),
                "movement" => db_update
                    .movement
                    .append(movement_table::parse_table_update(table_update)?),
                "needs" => db_update
                    .needs
                    .append(needs_table::parse_table_update(table_update)?),
                "passenger" => db_update
                    .passenger
                    .append(passenger_table::parse_table_update(table_update)?),
                "person" => db_update
                    .person
                    .append(person_table::parse_table_update(table_update)?),
                "personality" => db_update
                    .personality
                    .append(personality_table::parse_table_update(table_update)?),
                "position" => db_update
                    .position
                    .append(position_table::parse_table_update(table_update)?),
                "relationship" => db_update
                    .relationship
                    .append(relationship_table::parse_table_update(table_update)?),
                "room" => db_update
                    .room
                    .append(room_table::parse_table_update(table_update)?),
                "ship_config" => db_update
                    .ship_config
                    .append(ship_config_table::parse_table_update(table_update)?),
                "ship_resources" => db_update
                    .ship_resources
                    .append(ship_resources_table::parse_table_update(table_update)?),
                "ship_system" => db_update
                    .ship_system
                    .append(ship_system_table::parse_table_update(table_update)?),
                "skills" => db_update
                    .skills
                    .append(skills_table::parse_table_update(table_update)?),
                "subsystem" => db_update
                    .subsystem
                    .append(subsystem_table::parse_table_update(table_update)?),
                "system_component" => db_update
                    .system_component
                    .append(system_component_table::parse_table_update(table_update)?),
                "vertical_shaft" => db_update
                    .vertical_shaft
                    .append(vertical_shaft_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.activity = cache
            .apply_diff_to_table::<Activity>("activity", &self.activity)
            .with_updates_by_pk(|row| &row.person_id);
        diff.connected_player = cache
            .apply_diff_to_table::<ConnectedPlayer>("connected_player", &self.connected_player)
            .with_updates_by_pk(|row| &row.identity);
        diff.conversation = cache
            .apply_diff_to_table::<Conversation>("conversation", &self.conversation)
            .with_updates_by_pk(|row| &row.id);
        diff.corridor = cache
            .apply_diff_to_table::<Corridor>("corridor", &self.corridor)
            .with_updates_by_pk(|row| &row.id);
        diff.crew = cache
            .apply_diff_to_table::<Crew>("crew", &self.crew)
            .with_updates_by_pk(|row| &row.person_id);
        diff.deck_atmosphere = cache
            .apply_diff_to_table::<DeckAtmosphere>("deck_atmosphere", &self.deck_atmosphere)
            .with_updates_by_pk(|row| &row.deck);
        diff.door = cache
            .apply_diff_to_table::<Door>("door", &self.door)
            .with_updates_by_pk(|row| &row.id);
        diff.event = cache
            .apply_diff_to_table::<Event>("event", &self.event)
            .with_updates_by_pk(|row| &row.id);
        diff.graph_edge = cache
            .apply_diff_to_table::<GraphEdge>("graph_edge", &self.graph_edge)
            .with_updates_by_pk(|row| &row.id);
        diff.graph_node = cache
            .apply_diff_to_table::<GraphNode>("graph_node", &self.graph_node)
            .with_updates_by_pk(|row| &row.id);
        diff.in_conversation = cache
            .apply_diff_to_table::<InConversation>("in_conversation", &self.in_conversation)
            .with_updates_by_pk(|row| &row.person_id);
        diff.infra_edge = cache
            .apply_diff_to_table::<InfraEdge>("infra_edge", &self.infra_edge)
            .with_updates_by_pk(|row| &row.id);
        diff.maintenance_task = cache
            .apply_diff_to_table::<MaintenanceTask>("maintenance_task", &self.maintenance_task)
            .with_updates_by_pk(|row| &row.id);
        diff.movement = cache
            .apply_diff_to_table::<Movement>("movement", &self.movement)
            .with_updates_by_pk(|row| &row.person_id);
        diff.needs = cache
            .apply_diff_to_table::<Needs>("needs", &self.needs)
            .with_updates_by_pk(|row| &row.person_id);
        diff.passenger = cache
            .apply_diff_to_table::<Passenger>("passenger", &self.passenger)
            .with_updates_by_pk(|row| &row.person_id);
        diff.person = cache
            .apply_diff_to_table::<Person>("person", &self.person)
            .with_updates_by_pk(|row| &row.id);
        diff.personality = cache
            .apply_diff_to_table::<Personality>("personality", &self.personality)
            .with_updates_by_pk(|row| &row.person_id);
        diff.position = cache
            .apply_diff_to_table::<Position>("position", &self.position)
            .with_updates_by_pk(|row| &row.person_id);
        diff.relationship = cache
            .apply_diff_to_table::<Relationship>("relationship", &self.relationship)
            .with_updates_by_pk(|row| &row.id);
        diff.room = cache
            .apply_diff_to_table::<Room>("room", &self.room)
            .with_updates_by_pk(|row| &row.id);
        diff.ship_config = cache
            .apply_diff_to_table::<ShipConfig>("ship_config", &self.ship_config)
            .with_updates_by_pk(|row| &row.id);
        diff.ship_resources = cache
            .apply_diff_to_table::<ShipResources>("ship_resources", &self.ship_resources)
            .with_updates_by_pk(|row| &row.id);
        diff.ship_system = cache
            .apply_diff_to_table::<ShipSystem>("ship_system", &self.ship_system)
            .with_updates_by_pk(|row| &row.id);
        diff.skills = cache
            .apply_diff_to_table::<Skills>("skills", &self.skills)
            .with_updates_by_pk(|row| &row.person_id);
        diff.subsystem = cache
            .apply_diff_to_table::<Subsystem>("subsystem", &self.subsystem)
            .with_updates_by_pk(|row| &row.id);
        diff.system_component = cache
            .apply_diff_to_table::<SystemComponent>("system_component", &self.system_component)
            .with_updates_by_pk(|row| &row.id);
        diff.vertical_shaft = cache
            .apply_diff_to_table::<VerticalShaft>("vertical_shaft", &self.vertical_shaft)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    activity: __sdk::TableAppliedDiff<'r, Activity>,
    connected_player: __sdk::TableAppliedDiff<'r, ConnectedPlayer>,
    conversation: __sdk::TableAppliedDiff<'r, Conversation>,
    corridor: __sdk::TableAppliedDiff<'r, Corridor>,
    crew: __sdk::TableAppliedDiff<'r, Crew>,
    deck_atmosphere: __sdk::TableAppliedDiff<'r, DeckAtmosphere>,
    door: __sdk::TableAppliedDiff<'r, Door>,
    event: __sdk::TableAppliedDiff<'r, Event>,
    graph_edge: __sdk::TableAppliedDiff<'r, GraphEdge>,
    graph_node: __sdk::TableAppliedDiff<'r, GraphNode>,
    in_conversation: __sdk::TableAppliedDiff<'r, InConversation>,
    infra_edge: __sdk::TableAppliedDiff<'r, InfraEdge>,
    maintenance_task: __sdk::TableAppliedDiff<'r, MaintenanceTask>,
    movement: __sdk::TableAppliedDiff<'r, Movement>,
    needs: __sdk::TableAppliedDiff<'r, Needs>,
    passenger: __sdk::TableAppliedDiff<'r, Passenger>,
    person: __sdk::TableAppliedDiff<'r, Person>,
    personality: __sdk::TableAppliedDiff<'r, Personality>,
    position: __sdk::TableAppliedDiff<'r, Position>,
    relationship: __sdk::TableAppliedDiff<'r, Relationship>,
    room: __sdk::TableAppliedDiff<'r, Room>,
    ship_config: __sdk::TableAppliedDiff<'r, ShipConfig>,
    ship_resources: __sdk::TableAppliedDiff<'r, ShipResources>,
    ship_system: __sdk::TableAppliedDiff<'r, ShipSystem>,
    skills: __sdk::TableAppliedDiff<'r, Skills>,
    subsystem: __sdk::TableAppliedDiff<'r, Subsystem>,
    system_component: __sdk::TableAppliedDiff<'r, SystemComponent>,
    vertical_shaft: __sdk::TableAppliedDiff<'r, VerticalShaft>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Activity>("activity", &self.activity, event);
        callbacks.invoke_table_row_callbacks::<ConnectedPlayer>(
            "connected_player",
            &self.connected_player,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Conversation>(
            "conversation",
            &self.conversation,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Corridor>("corridor", &self.corridor, event);
        callbacks.invoke_table_row_callbacks::<Crew>("crew", &self.crew, event);
        callbacks.invoke_table_row_callbacks::<DeckAtmosphere>(
            "deck_atmosphere",
            &self.deck_atmosphere,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Door>("door", &self.door, event);
        callbacks.invoke_table_row_callbacks::<Event>("event", &self.event, event);
        callbacks.invoke_table_row_callbacks::<GraphEdge>("graph_edge", &self.graph_edge, event);
        callbacks.invoke_table_row_callbacks::<GraphNode>("graph_node", &self.graph_node, event);
        callbacks.invoke_table_row_callbacks::<InConversation>(
            "in_conversation",
            &self.in_conversation,
            event,
        );
        callbacks.invoke_table_row_callbacks::<InfraEdge>("infra_edge", &self.infra_edge, event);
        callbacks.invoke_table_row_callbacks::<MaintenanceTask>(
            "maintenance_task",
            &self.maintenance_task,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Movement>("movement", &self.movement, event);
        callbacks.invoke_table_row_callbacks::<Needs>("needs", &self.needs, event);
        callbacks.invoke_table_row_callbacks::<Passenger>("passenger", &self.passenger, event);
        callbacks.invoke_table_row_callbacks::<Person>("person", &self.person, event);
        callbacks.invoke_table_row_callbacks::<Personality>(
            "personality",
            &self.personality,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Position>("position", &self.position, event);
        callbacks.invoke_table_row_callbacks::<Relationship>(
            "relationship",
            &self.relationship,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Room>("room", &self.room, event);
        callbacks.invoke_table_row_callbacks::<ShipConfig>("ship_config", &self.ship_config, event);
        callbacks.invoke_table_row_callbacks::<ShipResources>(
            "ship_resources",
            &self.ship_resources,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ShipSystem>("ship_system", &self.ship_system, event);
        callbacks.invoke_table_row_callbacks::<Skills>("skills", &self.skills, event);
        callbacks.invoke_table_row_callbacks::<Subsystem>("subsystem", &self.subsystem, event);
        callbacks.invoke_table_row_callbacks::<SystemComponent>(
            "system_component",
            &self.system_component,
            event,
        );
        callbacks.invoke_table_row_callbacks::<VerticalShaft>(
            "vertical_shaft",
            &self.vertical_shaft,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

#[doc(hidden)]
/// The `set_reducer_flags` field of [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
/// Each method sets the flags for the reducer with the same name.
///
/// This type is currently unstable and may be removed without a major version bump.
pub struct SetReducerFlags {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for SetReducerFlags {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SetReducerFlags = SetReducerFlags,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SetReducerFlags = SetReducerFlags,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        activity_table::register_table(client_cache);
        connected_player_table::register_table(client_cache);
        conversation_table::register_table(client_cache);
        corridor_table::register_table(client_cache);
        crew_table::register_table(client_cache);
        deck_atmosphere_table::register_table(client_cache);
        door_table::register_table(client_cache);
        event_table::register_table(client_cache);
        graph_edge_table::register_table(client_cache);
        graph_node_table::register_table(client_cache);
        in_conversation_table::register_table(client_cache);
        infra_edge_table::register_table(client_cache);
        maintenance_task_table::register_table(client_cache);
        movement_table::register_table(client_cache);
        needs_table::register_table(client_cache);
        passenger_table::register_table(client_cache);
        person_table::register_table(client_cache);
        personality_table::register_table(client_cache);
        position_table::register_table(client_cache);
        relationship_table::register_table(client_cache);
        room_table::register_table(client_cache);
        ship_config_table::register_table(client_cache);
        ship_resources_table::register_table(client_cache);
        ship_system_table::register_table(client_cache);
        skills_table::register_table(client_cache);
        subsystem_table::register_table(client_cache);
        system_component_table::register_table(client_cache);
        vertical_shaft_table::register_table(client_cache);
    }
}
