// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MaintenanceTask {
    pub id: u64,
    pub component_id: u64,
    pub subsystem_id: u64,
    pub assigned_crew_id: Option<u64>,
    pub priority: f32,
    pub progress: f32,
    pub created_at: f64,
    pub required_skill: u8,
    pub duration_hours: f32,
}

impl __sdk::InModule for MaintenanceTask {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MaintenanceTask`.
///
/// Provides typed access to columns for query building.
pub struct MaintenanceTaskCols {
    pub id: __sdk::__query_builder::Col<MaintenanceTask, u64>,
    pub component_id: __sdk::__query_builder::Col<MaintenanceTask, u64>,
    pub subsystem_id: __sdk::__query_builder::Col<MaintenanceTask, u64>,
    pub assigned_crew_id: __sdk::__query_builder::Col<MaintenanceTask, Option<u64>>,
    pub priority: __sdk::__query_builder::Col<MaintenanceTask, f32>,
    pub progress: __sdk::__query_builder::Col<MaintenanceTask, f32>,
    pub created_at: __sdk::__query_builder::Col<MaintenanceTask, f64>,
    pub required_skill: __sdk::__query_builder::Col<MaintenanceTask, u8>,
    pub duration_hours: __sdk::__query_builder::Col<MaintenanceTask, f32>,
}

impl __sdk::__query_builder::HasCols for MaintenanceTask {
    type Cols = MaintenanceTaskCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MaintenanceTaskCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            component_id: __sdk::__query_builder::Col::new(table_name, "component_id"),
            subsystem_id: __sdk::__query_builder::Col::new(table_name, "subsystem_id"),
            assigned_crew_id: __sdk::__query_builder::Col::new(table_name, "assigned_crew_id"),
            priority: __sdk::__query_builder::Col::new(table_name, "priority"),
            progress: __sdk::__query_builder::Col::new(table_name, "progress"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            required_skill: __sdk::__query_builder::Col::new(table_name, "required_skill"),
            duration_hours: __sdk::__query_builder::Col::new(table_name, "duration_hours"),
        }
    }
}

/// Indexed column accessor struct for the table `MaintenanceTask`.
///
/// Provides typed access to indexed columns for query building.
pub struct MaintenanceTaskIxCols {
    pub id: __sdk::__query_builder::IxCol<MaintenanceTask, u64>,
}

impl __sdk::__query_builder::HasIxCols for MaintenanceTask {
    type IxCols = MaintenanceTaskIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MaintenanceTaskIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
