// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::maintenance_task_type::MaintenanceTask;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `maintenance_task`.
///
/// Obtain a handle from the [`MaintenanceTaskTableAccess::maintenance_task`] method on [`super::RemoteTables`],
/// like `ctx.db.maintenance_task()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.maintenance_task().on_insert(...)`.
pub struct MaintenanceTaskTableHandle<'ctx> {
    imp: __sdk::TableHandle<MaintenanceTask>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `maintenance_task`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MaintenanceTaskTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MaintenanceTaskTableHandle`], which mediates access to the table `maintenance_task`.
    fn maintenance_task(&self) -> MaintenanceTaskTableHandle<'_>;
}

impl MaintenanceTaskTableAccess for super::RemoteTables {
    fn maintenance_task(&self) -> MaintenanceTaskTableHandle<'_> {
        MaintenanceTaskTableHandle {
            imp: self.imp.get_table::<MaintenanceTask>("maintenance_task"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MaintenanceTaskInsertCallbackId(__sdk::CallbackId);
pub struct MaintenanceTaskDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MaintenanceTaskTableHandle<'ctx> {
    type Row = MaintenanceTask;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MaintenanceTask> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MaintenanceTaskInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MaintenanceTaskInsertCallbackId {
        MaintenanceTaskInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MaintenanceTaskInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MaintenanceTaskDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MaintenanceTaskDeleteCallbackId {
        MaintenanceTaskDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MaintenanceTaskDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MaintenanceTask>("maintenance_task");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct MaintenanceTaskUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MaintenanceTaskTableHandle<'ctx> {
    type UpdateCallbackId = MaintenanceTaskUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MaintenanceTaskUpdateCallbackId {
        MaintenanceTaskUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MaintenanceTaskUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MaintenanceTask>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MaintenanceTask>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `maintenance_task`,
/// which allows point queries on the field of the same name
/// via the [`MaintenanceTaskIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.maintenance_task().id().find(...)`.
pub struct MaintenanceTaskIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MaintenanceTask, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MaintenanceTaskTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `maintenance_task`.
    pub fn id(&self) -> MaintenanceTaskIdUnique<'ctx> {
        MaintenanceTaskIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MaintenanceTaskIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MaintenanceTask> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MaintenanceTask`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait maintenance_taskQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MaintenanceTask`.
    fn maintenance_task(&self) -> __sdk::__query_builder::Table<MaintenanceTask>;
}

impl maintenance_taskQueryTableAccess for __sdk::QueryTableAccessor {
    fn maintenance_task(&self) -> __sdk::__query_builder::Table<MaintenanceTask> {
        __sdk::__query_builder::Table::new("maintenance_task")
    }
}
