// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::movement_type::Movement;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `movement`.
///
/// Obtain a handle from the [`MovementTableAccess::movement`] method on [`super::RemoteTables`],
/// like `ctx.db.movement()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.movement().on_insert(...)`.
pub struct MovementTableHandle<'ctx> {
    imp: __sdk::TableHandle<Movement>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `movement`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MovementTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MovementTableHandle`], which mediates access to the table `movement`.
    fn movement(&self) -> MovementTableHandle<'_>;
}

impl MovementTableAccess for super::RemoteTables {
    fn movement(&self) -> MovementTableHandle<'_> {
        MovementTableHandle {
            imp: self.imp.get_table::<Movement>("movement"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MovementInsertCallbackId(__sdk::CallbackId);
pub struct MovementDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MovementTableHandle<'ctx> {
    type Row = Movement;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Movement> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MovementInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MovementInsertCallbackId {
        MovementInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MovementInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MovementDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MovementDeleteCallbackId {
        MovementDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MovementDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Movement>("movement");
    _table.add_unique_constraint::<u64>("person_id", |row| &row.person_id);
}
pub struct MovementUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MovementTableHandle<'ctx> {
    type UpdateCallbackId = MovementUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MovementUpdateCallbackId {
        MovementUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MovementUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Movement>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Movement>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `person_id` unique index on the table `movement`,
/// which allows point queries on the field of the same name
/// via the [`MovementPersonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.movement().person_id().find(...)`.
pub struct MovementPersonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Movement, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MovementTableHandle<'ctx> {
    /// Get a handle on the `person_id` unique index on the table `movement`.
    pub fn person_id(&self) -> MovementPersonIdUnique<'ctx> {
        MovementPersonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("person_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MovementPersonIdUnique<'ctx> {
    /// Find the subscribed row whose `person_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Movement> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Movement`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait movementQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Movement`.
    fn movement(&self) -> __sdk::__query_builder::Table<Movement>;
}

impl movementQueryTableAccess for __sdk::QueryTableAccessor {
    fn movement(&self) -> __sdk::__query_builder::Table<Movement> {
        __sdk::__query_builder::Table::new("movement")
    }
}
