// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Movement {
    pub person_id: u64,
    pub target_room_id: u32,
    pub target_x: f32,
    pub target_y: f32,
    pub target_z: f32,
    pub speed: f32,
    pub path: String,
    pub path_index: u32,
}

impl __sdk::InModule for Movement {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Movement`.
///
/// Provides typed access to columns for query building.
pub struct MovementCols {
    pub person_id: __sdk::__query_builder::Col<Movement, u64>,
    pub target_room_id: __sdk::__query_builder::Col<Movement, u32>,
    pub target_x: __sdk::__query_builder::Col<Movement, f32>,
    pub target_y: __sdk::__query_builder::Col<Movement, f32>,
    pub target_z: __sdk::__query_builder::Col<Movement, f32>,
    pub speed: __sdk::__query_builder::Col<Movement, f32>,
    pub path: __sdk::__query_builder::Col<Movement, String>,
    pub path_index: __sdk::__query_builder::Col<Movement, u32>,
}

impl __sdk::__query_builder::HasCols for Movement {
    type Cols = MovementCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MovementCols {
            person_id: __sdk::__query_builder::Col::new(table_name, "person_id"),
            target_room_id: __sdk::__query_builder::Col::new(table_name, "target_room_id"),
            target_x: __sdk::__query_builder::Col::new(table_name, "target_x"),
            target_y: __sdk::__query_builder::Col::new(table_name, "target_y"),
            target_z: __sdk::__query_builder::Col::new(table_name, "target_z"),
            speed: __sdk::__query_builder::Col::new(table_name, "speed"),
            path: __sdk::__query_builder::Col::new(table_name, "path"),
            path_index: __sdk::__query_builder::Col::new(table_name, "path_index"),
        }
    }
}

/// Indexed column accessor struct for the table `Movement`.
///
/// Provides typed access to indexed columns for query building.
pub struct MovementIxCols {
    pub person_id: __sdk::__query_builder::IxCol<Movement, u64>,
}

impl __sdk::__query_builder::HasIxCols for Movement {
    type IxCols = MovementIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MovementIxCols {
            person_id: __sdk::__query_builder::IxCol::new(table_name, "person_id"),
        }
    }
}
