// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Needs {
    pub person_id: u64,
    pub hunger: f32,
    pub fatigue: f32,
    pub social: f32,
    pub comfort: f32,
    pub hygiene: f32,
    pub health: f32,
    pub morale: f32,
}

impl __sdk::InModule for Needs {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Needs`.
///
/// Provides typed access to columns for query building.
pub struct NeedsCols {
    pub person_id: __sdk::__query_builder::Col<Needs, u64>,
    pub hunger: __sdk::__query_builder::Col<Needs, f32>,
    pub fatigue: __sdk::__query_builder::Col<Needs, f32>,
    pub social: __sdk::__query_builder::Col<Needs, f32>,
    pub comfort: __sdk::__query_builder::Col<Needs, f32>,
    pub hygiene: __sdk::__query_builder::Col<Needs, f32>,
    pub health: __sdk::__query_builder::Col<Needs, f32>,
    pub morale: __sdk::__query_builder::Col<Needs, f32>,
}

impl __sdk::__query_builder::HasCols for Needs {
    type Cols = NeedsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NeedsCols {
            person_id: __sdk::__query_builder::Col::new(table_name, "person_id"),
            hunger: __sdk::__query_builder::Col::new(table_name, "hunger"),
            fatigue: __sdk::__query_builder::Col::new(table_name, "fatigue"),
            social: __sdk::__query_builder::Col::new(table_name, "social"),
            comfort: __sdk::__query_builder::Col::new(table_name, "comfort"),
            hygiene: __sdk::__query_builder::Col::new(table_name, "hygiene"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            morale: __sdk::__query_builder::Col::new(table_name, "morale"),
        }
    }
}

/// Indexed column accessor struct for the table `Needs`.
///
/// Provides typed access to indexed columns for query building.
pub struct NeedsIxCols {
    pub person_id: __sdk::__query_builder::IxCol<Needs, u64>,
}

impl __sdk::__query_builder::HasIxCols for Needs {
    type IxCols = NeedsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NeedsIxCols {
            person_id: __sdk::__query_builder::IxCol::new(table_name, "person_id"),
        }
    }
}
