// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::needs_type::Needs;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `needs`.
///
/// Obtain a handle from the [`NeedsTableAccess::needs`] method on [`super::RemoteTables`],
/// like `ctx.db.needs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.needs().on_insert(...)`.
pub struct NeedsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Needs>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `needs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NeedsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NeedsTableHandle`], which mediates access to the table `needs`.
    fn needs(&self) -> NeedsTableHandle<'_>;
}

impl NeedsTableAccess for super::RemoteTables {
    fn needs(&self) -> NeedsTableHandle<'_> {
        NeedsTableHandle {
            imp: self.imp.get_table::<Needs>("needs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NeedsInsertCallbackId(__sdk::CallbackId);
pub struct NeedsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NeedsTableHandle<'ctx> {
    type Row = Needs;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Needs> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NeedsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NeedsInsertCallbackId {
        NeedsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NeedsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NeedsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NeedsDeleteCallbackId {
        NeedsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NeedsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Needs>("needs");
    _table.add_unique_constraint::<u64>("person_id", |row| &row.person_id);
}
pub struct NeedsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NeedsTableHandle<'ctx> {
    type UpdateCallbackId = NeedsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NeedsUpdateCallbackId {
        NeedsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NeedsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Needs>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Needs>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `person_id` unique index on the table `needs`,
/// which allows point queries on the field of the same name
/// via the [`NeedsPersonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.needs().person_id().find(...)`.
pub struct NeedsPersonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Needs, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NeedsTableHandle<'ctx> {
    /// Get a handle on the `person_id` unique index on the table `needs`.
    pub fn person_id(&self) -> NeedsPersonIdUnique<'ctx> {
        NeedsPersonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("person_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NeedsPersonIdUnique<'ctx> {
    /// Find the subscribed row whose `person_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Needs> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Needs`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait needsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Needs`.
    fn needs(&self) -> __sdk::__query_builder::Table<Needs>;
}

impl needsQueryTableAccess for __sdk::QueryTableAccessor {
    fn needs(&self) -> __sdk::__query_builder::Table<Needs> {
        __sdk::__query_builder::Table::new("needs")
    }
}
