// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Passenger {
    pub person_id: u64,
    pub cabin_class: u8,
    pub destination: String,
    pub profession: String,
}

impl __sdk::InModule for Passenger {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Passenger`.
///
/// Provides typed access to columns for query building.
pub struct PassengerCols {
    pub person_id: __sdk::__query_builder::Col<Passenger, u64>,
    pub cabin_class: __sdk::__query_builder::Col<Passenger, u8>,
    pub destination: __sdk::__query_builder::Col<Passenger, String>,
    pub profession: __sdk::__query_builder::Col<Passenger, String>,
}

impl __sdk::__query_builder::HasCols for Passenger {
    type Cols = PassengerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PassengerCols {
            person_id: __sdk::__query_builder::Col::new(table_name, "person_id"),
            cabin_class: __sdk::__query_builder::Col::new(table_name, "cabin_class"),
            destination: __sdk::__query_builder::Col::new(table_name, "destination"),
            profession: __sdk::__query_builder::Col::new(table_name, "profession"),
        }
    }
}

/// Indexed column accessor struct for the table `Passenger`.
///
/// Provides typed access to indexed columns for query building.
pub struct PassengerIxCols {
    pub person_id: __sdk::__query_builder::IxCol<Passenger, u64>,
}

impl __sdk::__query_builder::HasIxCols for Passenger {
    type IxCols = PassengerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PassengerIxCols {
            person_id: __sdk::__query_builder::IxCol::new(table_name, "person_id"),
        }
    }
}
