// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::passenger_type::Passenger;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `passenger`.
///
/// Obtain a handle from the [`PassengerTableAccess::passenger`] method on [`super::RemoteTables`],
/// like `ctx.db.passenger()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.passenger().on_insert(...)`.
pub struct PassengerTableHandle<'ctx> {
    imp: __sdk::TableHandle<Passenger>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `passenger`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PassengerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PassengerTableHandle`], which mediates access to the table `passenger`.
    fn passenger(&self) -> PassengerTableHandle<'_>;
}

impl PassengerTableAccess for super::RemoteTables {
    fn passenger(&self) -> PassengerTableHandle<'_> {
        PassengerTableHandle {
            imp: self.imp.get_table::<Passenger>("passenger"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PassengerInsertCallbackId(__sdk::CallbackId);
pub struct PassengerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PassengerTableHandle<'ctx> {
    type Row = Passenger;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Passenger> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PassengerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PassengerInsertCallbackId {
        PassengerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PassengerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PassengerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PassengerDeleteCallbackId {
        PassengerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PassengerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Passenger>("passenger");
    _table.add_unique_constraint::<u64>("person_id", |row| &row.person_id);
}
pub struct PassengerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PassengerTableHandle<'ctx> {
    type UpdateCallbackId = PassengerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PassengerUpdateCallbackId {
        PassengerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PassengerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Passenger>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Passenger>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `person_id` unique index on the table `passenger`,
/// which allows point queries on the field of the same name
/// via the [`PassengerPersonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.passenger().person_id().find(...)`.
pub struct PassengerPersonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Passenger, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PassengerTableHandle<'ctx> {
    /// Get a handle on the `person_id` unique index on the table `passenger`.
    pub fn person_id(&self) -> PassengerPersonIdUnique<'ctx> {
        PassengerPersonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("person_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PassengerPersonIdUnique<'ctx> {
    /// Find the subscribed row whose `person_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Passenger> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Passenger`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait passengerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Passenger`.
    fn passenger(&self) -> __sdk::__query_builder::Table<Passenger>;
}

impl passengerQueryTableAccess for __sdk::QueryTableAccessor {
    fn passenger(&self) -> __sdk::__query_builder::Table<Passenger> {
        __sdk::__query_builder::Table::new("passenger")
    }
}
