// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Person {
    pub id: u64,
    pub given_name: String,
    pub family_name: String,
    pub is_crew: bool,
    pub is_player: bool,
    pub owner_identity: Option<__sdk::Identity>,
}

impl __sdk::InModule for Person {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Person`.
///
/// Provides typed access to columns for query building.
pub struct PersonCols {
    pub id: __sdk::__query_builder::Col<Person, u64>,
    pub given_name: __sdk::__query_builder::Col<Person, String>,
    pub family_name: __sdk::__query_builder::Col<Person, String>,
    pub is_crew: __sdk::__query_builder::Col<Person, bool>,
    pub is_player: __sdk::__query_builder::Col<Person, bool>,
    pub owner_identity: __sdk::__query_builder::Col<Person, Option<__sdk::Identity>>,
}

impl __sdk::__query_builder::HasCols for Person {
    type Cols = PersonCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PersonCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            given_name: __sdk::__query_builder::Col::new(table_name, "given_name"),
            family_name: __sdk::__query_builder::Col::new(table_name, "family_name"),
            is_crew: __sdk::__query_builder::Col::new(table_name, "is_crew"),
            is_player: __sdk::__query_builder::Col::new(table_name, "is_player"),
            owner_identity: __sdk::__query_builder::Col::new(table_name, "owner_identity"),
        }
    }
}

/// Indexed column accessor struct for the table `Person`.
///
/// Provides typed access to indexed columns for query building.
pub struct PersonIxCols {
    pub id: __sdk::__query_builder::IxCol<Person, u64>,
}

impl __sdk::__query_builder::HasIxCols for Person {
    type IxCols = PersonIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PersonIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
