// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Personality {
    pub person_id: u64,
    pub openness: f32,
    pub conscientiousness: f32,
    pub extraversion: f32,
    pub agreeableness: f32,
    pub neuroticism: f32,
}

impl __sdk::InModule for Personality {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Personality`.
///
/// Provides typed access to columns for query building.
pub struct PersonalityCols {
    pub person_id: __sdk::__query_builder::Col<Personality, u64>,
    pub openness: __sdk::__query_builder::Col<Personality, f32>,
    pub conscientiousness: __sdk::__query_builder::Col<Personality, f32>,
    pub extraversion: __sdk::__query_builder::Col<Personality, f32>,
    pub agreeableness: __sdk::__query_builder::Col<Personality, f32>,
    pub neuroticism: __sdk::__query_builder::Col<Personality, f32>,
}

impl __sdk::__query_builder::HasCols for Personality {
    type Cols = PersonalityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PersonalityCols {
            person_id: __sdk::__query_builder::Col::new(table_name, "person_id"),
            openness: __sdk::__query_builder::Col::new(table_name, "openness"),
            conscientiousness: __sdk::__query_builder::Col::new(table_name, "conscientiousness"),
            extraversion: __sdk::__query_builder::Col::new(table_name, "extraversion"),
            agreeableness: __sdk::__query_builder::Col::new(table_name, "agreeableness"),
            neuroticism: __sdk::__query_builder::Col::new(table_name, "neuroticism"),
        }
    }
}

/// Indexed column accessor struct for the table `Personality`.
///
/// Provides typed access to indexed columns for query building.
pub struct PersonalityIxCols {
    pub person_id: __sdk::__query_builder::IxCol<Personality, u64>,
}

impl __sdk::__query_builder::HasIxCols for Personality {
    type IxCols = PersonalityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PersonalityIxCols {
            person_id: __sdk::__query_builder::IxCol::new(table_name, "person_id"),
        }
    }
}
