// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::personality_type::Personality;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `personality`.
///
/// Obtain a handle from the [`PersonalityTableAccess::personality`] method on [`super::RemoteTables`],
/// like `ctx.db.personality()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.personality().on_insert(...)`.
pub struct PersonalityTableHandle<'ctx> {
    imp: __sdk::TableHandle<Personality>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `personality`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PersonalityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PersonalityTableHandle`], which mediates access to the table `personality`.
    fn personality(&self) -> PersonalityTableHandle<'_>;
}

impl PersonalityTableAccess for super::RemoteTables {
    fn personality(&self) -> PersonalityTableHandle<'_> {
        PersonalityTableHandle {
            imp: self.imp.get_table::<Personality>("personality"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PersonalityInsertCallbackId(__sdk::CallbackId);
pub struct PersonalityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PersonalityTableHandle<'ctx> {
    type Row = Personality;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Personality> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PersonalityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PersonalityInsertCallbackId {
        PersonalityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PersonalityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PersonalityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PersonalityDeleteCallbackId {
        PersonalityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PersonalityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Personality>("personality");
    _table.add_unique_constraint::<u64>("person_id", |row| &row.person_id);
}
pub struct PersonalityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PersonalityTableHandle<'ctx> {
    type UpdateCallbackId = PersonalityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PersonalityUpdateCallbackId {
        PersonalityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PersonalityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Personality>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Personality>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `person_id` unique index on the table `personality`,
/// which allows point queries on the field of the same name
/// via the [`PersonalityPersonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.personality().person_id().find(...)`.
pub struct PersonalityPersonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Personality, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PersonalityTableHandle<'ctx> {
    /// Get a handle on the `person_id` unique index on the table `personality`.
    pub fn person_id(&self) -> PersonalityPersonIdUnique<'ctx> {
        PersonalityPersonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("person_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PersonalityPersonIdUnique<'ctx> {
    /// Find the subscribed row whose `person_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Personality> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Personality`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait personalityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Personality`.
    fn personality(&self) -> __sdk::__query_builder::Table<Personality>;
}

impl personalityQueryTableAccess for __sdk::QueryTableAccessor {
    fn personality(&self) -> __sdk::__query_builder::Table<Personality> {
        __sdk::__query_builder::Table::new("personality")
    }
}
