// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerInteractArgs {
    pub target_person_id: u64,
}

impl From<PlayerInteractArgs> for super::Reducer {
    fn from(args: PlayerInteractArgs) -> Self {
        Self::PlayerInteract {
            target_person_id: args.target_person_id,
        }
    }
}

impl __sdk::InModule for PlayerInteractArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerInteractCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_interact`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_interact {
    /// Request that the remote module invoke the reducer `player_interact` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_interact`] callbacks.
    fn player_interact(&self, target_person_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_interact`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerInteractCallbackId`] can be passed to [`Self::remove_on_player_interact`]
    /// to cancel the callback.
    fn on_player_interact(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> PlayerInteractCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_interact`],
    /// causing it not to run in the future.
    fn remove_on_player_interact(&self, callback: PlayerInteractCallbackId);
}

impl player_interact for super::RemoteReducers {
    fn player_interact(&self, target_person_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("player_interact", PlayerInteractArgs { target_person_id })
    }
    fn on_player_interact(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> PlayerInteractCallbackId {
        PlayerInteractCallbackId(self.imp.on_reducer(
            "player_interact",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerInteract { target_person_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, target_person_id)
            }),
        ))
    }
    fn remove_on_player_interact(&self, callback: PlayerInteractCallbackId) {
        self.imp.remove_on_reducer("player_interact", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_interact`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_interact {
    /// Set the call-reducer flags for the reducer `player_interact` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_interact(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_interact for super::SetReducerFlags {
    fn player_interact(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_interact", flags);
    }
}
