// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerJoinArgs {
    pub given_name: String,
    pub family_name: String,
    pub is_crew: bool,
}

impl From<PlayerJoinArgs> for super::Reducer {
    fn from(args: PlayerJoinArgs) -> Self {
        Self::PlayerJoin {
            given_name: args.given_name,
            family_name: args.family_name,
            is_crew: args.is_crew,
        }
    }
}

impl __sdk::InModule for PlayerJoinArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerJoinCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_join`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_join {
    /// Request that the remote module invoke the reducer `player_join` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_join`] callbacks.
    fn player_join(
        &self,
        given_name: String,
        family_name: String,
        is_crew: bool,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_join`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerJoinCallbackId`] can be passed to [`Self::remove_on_player_join`]
    /// to cancel the callback.
    fn on_player_join(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String, &bool) + Send + 'static,
    ) -> PlayerJoinCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_join`],
    /// causing it not to run in the future.
    fn remove_on_player_join(&self, callback: PlayerJoinCallbackId);
}

impl player_join for super::RemoteReducers {
    fn player_join(
        &self,
        given_name: String,
        family_name: String,
        is_crew: bool,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "player_join",
            PlayerJoinArgs {
                given_name,
                family_name,
                is_crew,
            },
        )
    }
    fn on_player_join(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &bool) + Send + 'static,
    ) -> PlayerJoinCallbackId {
        PlayerJoinCallbackId(self.imp.on_reducer(
            "player_join",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::PlayerJoin {
                                    given_name,
                                    family_name,
                                    is_crew,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, given_name, family_name, is_crew)
            }),
        ))
    }
    fn remove_on_player_join(&self, callback: PlayerJoinCallbackId) {
        self.imp.remove_on_reducer("player_join", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_join`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_join {
    /// Set the call-reducer flags for the reducer `player_join` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_join(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_join for super::SetReducerFlags {
    fn player_join(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_join", flags);
    }
}
