// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerActionArgs {
    pub action: u8,
}

impl From<PlayerActionArgs> for super::Reducer {
    fn from(args: PlayerActionArgs) -> Self {
        Self::PlayerAction {
            action: args.action,
        }
    }
}

impl __sdk::InModule for PlayerActionArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerActionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_action`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_action {
    /// Request that the remote module invoke the reducer `player_action` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_action`] callbacks.
    fn player_action(&self, action: u8) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_action`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerActionCallbackId`] can be passed to [`Self::remove_on_player_action`]
    /// to cancel the callback.
    fn on_player_action(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u8) + Send + 'static,
    ) -> PlayerActionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_action`],
    /// causing it not to run in the future.
    fn remove_on_player_action(&self, callback: PlayerActionCallbackId);
}

impl player_action for super::RemoteReducers {
    fn player_action(&self, action: u8) -> __sdk::Result<()> {
        self.imp
            .call_reducer("player_action", PlayerActionArgs { action })
    }
    fn on_player_action(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u8) + Send + 'static,
    ) -> PlayerActionCallbackId {
        PlayerActionCallbackId(self.imp.on_reducer(
            "player_action",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerAction { action },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, action)
            }),
        ))
    }
    fn remove_on_player_action(&self, callback: PlayerActionCallbackId) {
        self.imp.remove_on_reducer("player_action", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_action`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_action {
    /// Set the call-reducer flags for the reducer `player_action` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_action(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_action for super::SetReducerFlags {
    fn player_action(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_action", flags);
    }
}
