// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Position {
    pub person_id: u64,
    pub room_id: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl __sdk::InModule for Position {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Position`.
///
/// Provides typed access to columns for query building.
pub struct PositionCols {
    pub person_id: __sdk::__query_builder::Col<Position, u64>,
    pub room_id: __sdk::__query_builder::Col<Position, u32>,
    pub x: __sdk::__query_builder::Col<Position, f32>,
    pub y: __sdk::__query_builder::Col<Position, f32>,
    pub z: __sdk::__query_builder::Col<Position, f32>,
}

impl __sdk::__query_builder::HasCols for Position {
    type Cols = PositionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PositionCols {
            person_id: __sdk::__query_builder::Col::new(table_name, "person_id"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
        }
    }
}

/// Indexed column accessor struct for the table `Position`.
///
/// Provides typed access to indexed columns for query building.
pub struct PositionIxCols {
    pub person_id: __sdk::__query_builder::IxCol<Position, u64>,
}

impl __sdk::__query_builder::HasIxCols for Position {
    type IxCols = PositionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PositionIxCols {
            person_id: __sdk::__query_builder::IxCol::new(table_name, "person_id"),
        }
    }
}
