// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::position_type::Position;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `position`.
///
/// Obtain a handle from the [`PositionTableAccess::position`] method on [`super::RemoteTables`],
/// like `ctx.db.position()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.position().on_insert(...)`.
pub struct PositionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Position>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `position`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PositionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PositionTableHandle`], which mediates access to the table `position`.
    fn position(&self) -> PositionTableHandle<'_>;
}

impl PositionTableAccess for super::RemoteTables {
    fn position(&self) -> PositionTableHandle<'_> {
        PositionTableHandle {
            imp: self.imp.get_table::<Position>("position"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PositionInsertCallbackId(__sdk::CallbackId);
pub struct PositionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PositionTableHandle<'ctx> {
    type Row = Position;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Position> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PositionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PositionInsertCallbackId {
        PositionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PositionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PositionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PositionDeleteCallbackId {
        PositionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PositionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Position>("position");
    _table.add_unique_constraint::<u64>("person_id", |row| &row.person_id);
}
pub struct PositionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PositionTableHandle<'ctx> {
    type UpdateCallbackId = PositionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PositionUpdateCallbackId {
        PositionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PositionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Position>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Position>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `person_id` unique index on the table `position`,
/// which allows point queries on the field of the same name
/// via the [`PositionPersonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.position().person_id().find(...)`.
pub struct PositionPersonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Position, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PositionTableHandle<'ctx> {
    /// Get a handle on the `person_id` unique index on the table `position`.
    pub fn person_id(&self) -> PositionPersonIdUnique<'ctx> {
        PositionPersonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("person_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PositionPersonIdUnique<'ctx> {
    /// Find the subscribed row whose `person_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Position> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Position`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait positionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Position`.
    fn position(&self) -> __sdk::__query_builder::Table<Position>;
}

impl positionQueryTableAccess for __sdk::QueryTableAccessor {
    fn position(&self) -> __sdk::__query_builder::Table<Position> {
        __sdk::__query_builder::Table::new("position")
    }
}
