// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::relationship_type::Relationship;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `relationship`.
///
/// Obtain a handle from the [`RelationshipTableAccess::relationship`] method on [`super::RemoteTables`],
/// like `ctx.db.relationship()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.relationship().on_insert(...)`.
pub struct RelationshipTableHandle<'ctx> {
    imp: __sdk::TableHandle<Relationship>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `relationship`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RelationshipTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RelationshipTableHandle`], which mediates access to the table `relationship`.
    fn relationship(&self) -> RelationshipTableHandle<'_>;
}

impl RelationshipTableAccess for super::RemoteTables {
    fn relationship(&self) -> RelationshipTableHandle<'_> {
        RelationshipTableHandle {
            imp: self.imp.get_table::<Relationship>("relationship"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RelationshipInsertCallbackId(__sdk::CallbackId);
pub struct RelationshipDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RelationshipTableHandle<'ctx> {
    type Row = Relationship;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Relationship> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RelationshipInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RelationshipInsertCallbackId {
        RelationshipInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RelationshipInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RelationshipDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RelationshipDeleteCallbackId {
        RelationshipDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RelationshipDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Relationship>("relationship");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct RelationshipUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RelationshipTableHandle<'ctx> {
    type UpdateCallbackId = RelationshipUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RelationshipUpdateCallbackId {
        RelationshipUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RelationshipUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Relationship>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Relationship>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `relationship`,
/// which allows point queries on the field of the same name
/// via the [`RelationshipIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.relationship().id().find(...)`.
pub struct RelationshipIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Relationship, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RelationshipTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `relationship`.
    pub fn id(&self) -> RelationshipIdUnique<'ctx> {
        RelationshipIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RelationshipIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Relationship> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Relationship`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait relationshipQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Relationship`.
    fn relationship(&self) -> __sdk::__query_builder::Table<Relationship>;
}

impl relationshipQueryTableAccess for __sdk::QueryTableAccessor {
    fn relationship(&self) -> __sdk::__query_builder::Table<Relationship> {
        __sdk::__query_builder::Table::new("relationship")
    }
}
