// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Relationship {
    pub id: u64,
    pub person_a: u64,
    pub person_b: u64,
    pub relationship_type: u8,
    pub strength: f32,
    pub familiarity: f32,
    pub last_interaction: f64,
}

impl __sdk::InModule for Relationship {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Relationship`.
///
/// Provides typed access to columns for query building.
pub struct RelationshipCols {
    pub id: __sdk::__query_builder::Col<Relationship, u64>,
    pub person_a: __sdk::__query_builder::Col<Relationship, u64>,
    pub person_b: __sdk::__query_builder::Col<Relationship, u64>,
    pub relationship_type: __sdk::__query_builder::Col<Relationship, u8>,
    pub strength: __sdk::__query_builder::Col<Relationship, f32>,
    pub familiarity: __sdk::__query_builder::Col<Relationship, f32>,
    pub last_interaction: __sdk::__query_builder::Col<Relationship, f64>,
}

impl __sdk::__query_builder::HasCols for Relationship {
    type Cols = RelationshipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RelationshipCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            person_a: __sdk::__query_builder::Col::new(table_name, "person_a"),
            person_b: __sdk::__query_builder::Col::new(table_name, "person_b"),
            relationship_type: __sdk::__query_builder::Col::new(table_name, "relationship_type"),
            strength: __sdk::__query_builder::Col::new(table_name, "strength"),
            familiarity: __sdk::__query_builder::Col::new(table_name, "familiarity"),
            last_interaction: __sdk::__query_builder::Col::new(table_name, "last_interaction"),
        }
    }
}

/// Indexed column accessor struct for the table `Relationship`.
///
/// Provides typed access to indexed columns for query building.
pub struct RelationshipIxCols {
    pub id: __sdk::__query_builder::IxCol<Relationship, u64>,
}

impl __sdk::__query_builder::HasIxCols for Relationship {
    type IxCols = RelationshipIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RelationshipIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
