// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Room {
    pub id: u32,
    pub node_id: u64,
    pub name: String,
    pub room_type: u8,
    pub deck: i32,
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
    pub capacity: u32,
    pub ceiling_height: f32,
    pub deck_span: u8,
    pub cells: Vec<u8>,
}

impl __sdk::InModule for Room {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Room`.
///
/// Provides typed access to columns for query building.
pub struct RoomCols {
    pub id: __sdk::__query_builder::Col<Room, u32>,
    pub node_id: __sdk::__query_builder::Col<Room, u64>,
    pub name: __sdk::__query_builder::Col<Room, String>,
    pub room_type: __sdk::__query_builder::Col<Room, u8>,
    pub deck: __sdk::__query_builder::Col<Room, i32>,
    pub x: __sdk::__query_builder::Col<Room, f32>,
    pub y: __sdk::__query_builder::Col<Room, f32>,
    pub width: __sdk::__query_builder::Col<Room, f32>,
    pub height: __sdk::__query_builder::Col<Room, f32>,
    pub capacity: __sdk::__query_builder::Col<Room, u32>,
    pub ceiling_height: __sdk::__query_builder::Col<Room, f32>,
    pub deck_span: __sdk::__query_builder::Col<Room, u8>,
    pub cells: __sdk::__query_builder::Col<Room, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for Room {
    type Cols = RoomCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RoomCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            room_type: __sdk::__query_builder::Col::new(table_name, "room_type"),
            deck: __sdk::__query_builder::Col::new(table_name, "deck"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            width: __sdk::__query_builder::Col::new(table_name, "width"),
            height: __sdk::__query_builder::Col::new(table_name, "height"),
            capacity: __sdk::__query_builder::Col::new(table_name, "capacity"),
            ceiling_height: __sdk::__query_builder::Col::new(table_name, "ceiling_height"),
            deck_span: __sdk::__query_builder::Col::new(table_name, "deck_span"),
            cells: __sdk::__query_builder::Col::new(table_name, "cells"),
        }
    }
}

/// Indexed column accessor struct for the table `Room`.
///
/// Provides typed access to indexed columns for query building.
pub struct RoomIxCols {
    pub id: __sdk::__query_builder::IxCol<Room, u32>,
}

impl __sdk::__query_builder::HasIxCols for Room {
    type IxCols = RoomIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RoomIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
