// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetTimeScaleArgs {
    pub scale: f32,
}

impl From<SetTimeScaleArgs> for super::Reducer {
    fn from(args: SetTimeScaleArgs) -> Self {
        Self::SetTimeScale { scale: args.scale }
    }
}

impl __sdk::InModule for SetTimeScaleArgs {
    type Module = super::RemoteModule;
}

pub struct SetTimeScaleCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_time_scale`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_time_scale {
    /// Request that the remote module invoke the reducer `set_time_scale` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_time_scale`] callbacks.
    fn set_time_scale(&self, scale: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_time_scale`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetTimeScaleCallbackId`] can be passed to [`Self::remove_on_set_time_scale`]
    /// to cancel the callback.
    fn on_set_time_scale(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &f32) + Send + 'static,
    ) -> SetTimeScaleCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_time_scale`],
    /// causing it not to run in the future.
    fn remove_on_set_time_scale(&self, callback: SetTimeScaleCallbackId);
}

impl set_time_scale for super::RemoteReducers {
    fn set_time_scale(&self, scale: f32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("set_time_scale", SetTimeScaleArgs { scale })
    }
    fn on_set_time_scale(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &f32) + Send + 'static,
    ) -> SetTimeScaleCallbackId {
        SetTimeScaleCallbackId(self.imp.on_reducer(
            "set_time_scale",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetTimeScale { scale },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, scale)
            }),
        ))
    }
    fn remove_on_set_time_scale(&self, callback: SetTimeScaleCallbackId) {
        self.imp.remove_on_reducer("set_time_scale", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_time_scale`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_time_scale {
    /// Set the call-reducer flags for the reducer `set_time_scale` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_time_scale(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_time_scale for super::SetReducerFlags {
    fn set_time_scale(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_time_scale", flags);
    }
}
