// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetPausedArgs {
    pub paused: bool,
}

impl From<SetPausedArgs> for super::Reducer {
    fn from(args: SetPausedArgs) -> Self {
        Self::SetPaused {
            paused: args.paused,
        }
    }
}

impl __sdk::InModule for SetPausedArgs {
    type Module = super::RemoteModule;
}

pub struct SetPausedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_paused`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_paused {
    /// Request that the remote module invoke the reducer `set_paused` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_paused`] callbacks.
    fn set_paused(&self, paused: bool) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_paused`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetPausedCallbackId`] can be passed to [`Self::remove_on_set_paused`]
    /// to cancel the callback.
    fn on_set_paused(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &bool) + Send + 'static,
    ) -> SetPausedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_paused`],
    /// causing it not to run in the future.
    fn remove_on_set_paused(&self, callback: SetPausedCallbackId);
}

impl set_paused for super::RemoteReducers {
    fn set_paused(&self, paused: bool) -> __sdk::Result<()> {
        self.imp
            .call_reducer("set_paused", SetPausedArgs { paused })
    }
    fn on_set_paused(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &bool) + Send + 'static,
    ) -> SetPausedCallbackId {
        SetPausedCallbackId(self.imp.on_reducer(
            "set_paused",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetPaused { paused },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, paused)
            }),
        ))
    }
    fn remove_on_set_paused(&self, callback: SetPausedCallbackId) {
        self.imp.remove_on_reducer("set_paused", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_paused`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_paused {
    /// Set the call-reducer flags for the reducer `set_paused` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_paused(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_paused for super::SetReducerFlags {
    fn set_paused(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_paused", flags);
    }
}
