// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipSystem {
    pub id: u64,
    pub name: String,
    pub system_type: u8,
    pub overall_health: f32,
    pub overall_status: u8,
    pub priority: u8,
}

impl __sdk::InModule for ShipSystem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ShipSystem`.
///
/// Provides typed access to columns for query building.
pub struct ShipSystemCols {
    pub id: __sdk::__query_builder::Col<ShipSystem, u64>,
    pub name: __sdk::__query_builder::Col<ShipSystem, String>,
    pub system_type: __sdk::__query_builder::Col<ShipSystem, u8>,
    pub overall_health: __sdk::__query_builder::Col<ShipSystem, f32>,
    pub overall_status: __sdk::__query_builder::Col<ShipSystem, u8>,
    pub priority: __sdk::__query_builder::Col<ShipSystem, u8>,
}

impl __sdk::__query_builder::HasCols for ShipSystem {
    type Cols = ShipSystemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipSystemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            system_type: __sdk::__query_builder::Col::new(table_name, "system_type"),
            overall_health: __sdk::__query_builder::Col::new(table_name, "overall_health"),
            overall_status: __sdk::__query_builder::Col::new(table_name, "overall_status"),
            priority: __sdk::__query_builder::Col::new(table_name, "priority"),
        }
    }
}

/// Indexed column accessor struct for the table `ShipSystem`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipSystemIxCols {
    pub id: __sdk::__query_builder::IxCol<ShipSystem, u64>,
}

impl __sdk::__query_builder::HasIxCols for ShipSystem {
    type IxCols = ShipSystemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipSystemIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
