// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_config_type::ShipConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_config`.
///
/// Obtain a handle from the [`ShipConfigTableAccess::ship_config`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_config().on_insert(...)`.
pub struct ShipConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipConfigTableHandle`], which mediates access to the table `ship_config`.
    fn ship_config(&self) -> ShipConfigTableHandle<'_>;
}

impl ShipConfigTableAccess for super::RemoteTables {
    fn ship_config(&self) -> ShipConfigTableHandle<'_> {
        ShipConfigTableHandle {
            imp: self.imp.get_table::<ShipConfig>("ship_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipConfigInsertCallbackId(__sdk::CallbackId);
pub struct ShipConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipConfigTableHandle<'ctx> {
    type Row = ShipConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipConfigInsertCallbackId {
        ShipConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipConfigDeleteCallbackId {
        ShipConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipConfig>("ship_config");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct ShipConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipConfigTableHandle<'ctx> {
    type UpdateCallbackId = ShipConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipConfigUpdateCallbackId {
        ShipConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ship_config`,
/// which allows point queries on the field of the same name
/// via the [`ShipConfigIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_config().id().find(...)`.
pub struct ShipConfigIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipConfig, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipConfigTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ship_config`.
    pub fn id(&self) -> ShipConfigIdUnique<'ctx> {
        ShipConfigIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipConfigIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ShipConfig> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ShipConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ship_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ShipConfig`.
    fn ship_config(&self) -> __sdk::__query_builder::Table<ShipConfig>;
}

impl ship_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn ship_config(&self) -> __sdk::__query_builder::Table<ShipConfig> {
        __sdk::__query_builder::Table::new("ship_config")
    }
}
