// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipResources {
    pub id: u32,
    pub power: f32,
    pub water: f32,
    pub oxygen: f32,
    pub food: f32,
    pub fuel: f32,
    pub spare_parts: f32,
    pub power_cap: f32,
    pub water_cap: f32,
    pub oxygen_cap: f32,
    pub food_cap: f32,
    pub fuel_cap: f32,
    pub spare_parts_cap: f32,
}

impl __sdk::InModule for ShipResources {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ShipResources`.
///
/// Provides typed access to columns for query building.
pub struct ShipResourcesCols {
    pub id: __sdk::__query_builder::Col<ShipResources, u32>,
    pub power: __sdk::__query_builder::Col<ShipResources, f32>,
    pub water: __sdk::__query_builder::Col<ShipResources, f32>,
    pub oxygen: __sdk::__query_builder::Col<ShipResources, f32>,
    pub food: __sdk::__query_builder::Col<ShipResources, f32>,
    pub fuel: __sdk::__query_builder::Col<ShipResources, f32>,
    pub spare_parts: __sdk::__query_builder::Col<ShipResources, f32>,
    pub power_cap: __sdk::__query_builder::Col<ShipResources, f32>,
    pub water_cap: __sdk::__query_builder::Col<ShipResources, f32>,
    pub oxygen_cap: __sdk::__query_builder::Col<ShipResources, f32>,
    pub food_cap: __sdk::__query_builder::Col<ShipResources, f32>,
    pub fuel_cap: __sdk::__query_builder::Col<ShipResources, f32>,
    pub spare_parts_cap: __sdk::__query_builder::Col<ShipResources, f32>,
}

impl __sdk::__query_builder::HasCols for ShipResources {
    type Cols = ShipResourcesCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipResourcesCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            power: __sdk::__query_builder::Col::new(table_name, "power"),
            water: __sdk::__query_builder::Col::new(table_name, "water"),
            oxygen: __sdk::__query_builder::Col::new(table_name, "oxygen"),
            food: __sdk::__query_builder::Col::new(table_name, "food"),
            fuel: __sdk::__query_builder::Col::new(table_name, "fuel"),
            spare_parts: __sdk::__query_builder::Col::new(table_name, "spare_parts"),
            power_cap: __sdk::__query_builder::Col::new(table_name, "power_cap"),
            water_cap: __sdk::__query_builder::Col::new(table_name, "water_cap"),
            oxygen_cap: __sdk::__query_builder::Col::new(table_name, "oxygen_cap"),
            food_cap: __sdk::__query_builder::Col::new(table_name, "food_cap"),
            fuel_cap: __sdk::__query_builder::Col::new(table_name, "fuel_cap"),
            spare_parts_cap: __sdk::__query_builder::Col::new(table_name, "spare_parts_cap"),
        }
    }
}

/// Indexed column accessor struct for the table `ShipResources`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipResourcesIxCols {
    pub id: __sdk::__query_builder::IxCol<ShipResources, u32>,
}

impl __sdk::__query_builder::HasIxCols for ShipResources {
    type IxCols = ShipResourcesIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipResourcesIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
