// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_resources_type::ShipResources;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_resources`.
///
/// Obtain a handle from the [`ShipResourcesTableAccess::ship_resources`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_resources()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_resources().on_insert(...)`.
pub struct ShipResourcesTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipResources>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_resources`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipResourcesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipResourcesTableHandle`], which mediates access to the table `ship_resources`.
    fn ship_resources(&self) -> ShipResourcesTableHandle<'_>;
}

impl ShipResourcesTableAccess for super::RemoteTables {
    fn ship_resources(&self) -> ShipResourcesTableHandle<'_> {
        ShipResourcesTableHandle {
            imp: self.imp.get_table::<ShipResources>("ship_resources"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipResourcesInsertCallbackId(__sdk::CallbackId);
pub struct ShipResourcesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipResourcesTableHandle<'ctx> {
    type Row = ShipResources;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipResources> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipResourcesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipResourcesInsertCallbackId {
        ShipResourcesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipResourcesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipResourcesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipResourcesDeleteCallbackId {
        ShipResourcesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipResourcesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipResources>("ship_resources");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct ShipResourcesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipResourcesTableHandle<'ctx> {
    type UpdateCallbackId = ShipResourcesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipResourcesUpdateCallbackId {
        ShipResourcesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipResourcesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipResources>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipResources>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ship_resources`,
/// which allows point queries on the field of the same name
/// via the [`ShipResourcesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_resources().id().find(...)`.
pub struct ShipResourcesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipResources, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipResourcesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ship_resources`.
    pub fn id(&self) -> ShipResourcesIdUnique<'ctx> {
        ShipResourcesIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipResourcesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ShipResources> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ShipResources`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ship_resourcesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ShipResources`.
    fn ship_resources(&self) -> __sdk::__query_builder::Table<ShipResources>;
}

impl ship_resourcesQueryTableAccess for __sdk::QueryTableAccessor {
    fn ship_resources(&self) -> __sdk::__query_builder::Table<ShipResources> {
        __sdk::__query_builder::Table::new("ship_resources")
    }
}
