// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipConfig {
    pub id: u32,
    pub name: String,
    pub deck_count: u32,
    pub crew_count: u32,
    pub passenger_count: u32,
    pub sim_time: f64,
    pub time_scale: f32,
    pub paused: bool,
}

impl __sdk::InModule for ShipConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ShipConfig`.
///
/// Provides typed access to columns for query building.
pub struct ShipConfigCols {
    pub id: __sdk::__query_builder::Col<ShipConfig, u32>,
    pub name: __sdk::__query_builder::Col<ShipConfig, String>,
    pub deck_count: __sdk::__query_builder::Col<ShipConfig, u32>,
    pub crew_count: __sdk::__query_builder::Col<ShipConfig, u32>,
    pub passenger_count: __sdk::__query_builder::Col<ShipConfig, u32>,
    pub sim_time: __sdk::__query_builder::Col<ShipConfig, f64>,
    pub time_scale: __sdk::__query_builder::Col<ShipConfig, f32>,
    pub paused: __sdk::__query_builder::Col<ShipConfig, bool>,
}

impl __sdk::__query_builder::HasCols for ShipConfig {
    type Cols = ShipConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipConfigCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            deck_count: __sdk::__query_builder::Col::new(table_name, "deck_count"),
            crew_count: __sdk::__query_builder::Col::new(table_name, "crew_count"),
            passenger_count: __sdk::__query_builder::Col::new(table_name, "passenger_count"),
            sim_time: __sdk::__query_builder::Col::new(table_name, "sim_time"),
            time_scale: __sdk::__query_builder::Col::new(table_name, "time_scale"),
            paused: __sdk::__query_builder::Col::new(table_name, "paused"),
        }
    }
}

/// Indexed column accessor struct for the table `ShipConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipConfigIxCols {
    pub id: __sdk::__query_builder::IxCol<ShipConfig, u32>,
}

impl __sdk::__query_builder::HasIxCols for ShipConfig {
    type IxCols = ShipConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipConfigIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
