// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_system_type::ShipSystem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_system`.
///
/// Obtain a handle from the [`ShipSystemTableAccess::ship_system`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_system()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_system().on_insert(...)`.
pub struct ShipSystemTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipSystem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_system`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipSystemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipSystemTableHandle`], which mediates access to the table `ship_system`.
    fn ship_system(&self) -> ShipSystemTableHandle<'_>;
}

impl ShipSystemTableAccess for super::RemoteTables {
    fn ship_system(&self) -> ShipSystemTableHandle<'_> {
        ShipSystemTableHandle {
            imp: self.imp.get_table::<ShipSystem>("ship_system"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipSystemInsertCallbackId(__sdk::CallbackId);
pub struct ShipSystemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipSystemTableHandle<'ctx> {
    type Row = ShipSystem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipSystem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipSystemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipSystemInsertCallbackId {
        ShipSystemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipSystemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipSystemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipSystemDeleteCallbackId {
        ShipSystemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipSystemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipSystem>("ship_system");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ShipSystemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipSystemTableHandle<'ctx> {
    type UpdateCallbackId = ShipSystemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipSystemUpdateCallbackId {
        ShipSystemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipSystemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ShipSystem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipSystem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ship_system`,
/// which allows point queries on the field of the same name
/// via the [`ShipSystemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_system().id().find(...)`.
pub struct ShipSystemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipSystem, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipSystemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ship_system`.
    pub fn id(&self) -> ShipSystemIdUnique<'ctx> {
        ShipSystemIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipSystemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipSystem> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ShipSystem`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ship_systemQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ShipSystem`.
    fn ship_system(&self) -> __sdk::__query_builder::Table<ShipSystem>;
}

impl ship_systemQueryTableAccess for __sdk::QueryTableAccessor {
    fn ship_system(&self) -> __sdk::__query_builder::Table<ShipSystem> {
        __sdk::__query_builder::Table::new("ship_system")
    }
}
