// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::skills_type::Skills;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `skills`.
///
/// Obtain a handle from the [`SkillsTableAccess::skills`] method on [`super::RemoteTables`],
/// like `ctx.db.skills()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skills().on_insert(...)`.
pub struct SkillsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Skills>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `skills`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SkillsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SkillsTableHandle`], which mediates access to the table `skills`.
    fn skills(&self) -> SkillsTableHandle<'_>;
}

impl SkillsTableAccess for super::RemoteTables {
    fn skills(&self) -> SkillsTableHandle<'_> {
        SkillsTableHandle {
            imp: self.imp.get_table::<Skills>("skills"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SkillsInsertCallbackId(__sdk::CallbackId);
pub struct SkillsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SkillsTableHandle<'ctx> {
    type Row = Skills;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Skills> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SkillsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillsInsertCallbackId {
        SkillsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SkillsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SkillsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillsDeleteCallbackId {
        SkillsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SkillsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Skills>("skills");
    _table.add_unique_constraint::<u64>("person_id", |row| &row.person_id);
}
pub struct SkillsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SkillsTableHandle<'ctx> {
    type UpdateCallbackId = SkillsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SkillsUpdateCallbackId {
        SkillsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SkillsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Skills>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Skills>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `person_id` unique index on the table `skills`,
/// which allows point queries on the field of the same name
/// via the [`SkillsPersonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skills().person_id().find(...)`.
pub struct SkillsPersonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Skills, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SkillsTableHandle<'ctx> {
    /// Get a handle on the `person_id` unique index on the table `skills`.
    pub fn person_id(&self) -> SkillsPersonIdUnique<'ctx> {
        SkillsPersonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("person_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SkillsPersonIdUnique<'ctx> {
    /// Find the subscribed row whose `person_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Skills> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Skills`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait skillsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Skills`.
    fn skills(&self) -> __sdk::__query_builder::Table<Skills>;
}

impl skillsQueryTableAccess for __sdk::QueryTableAccessor {
    fn skills(&self) -> __sdk::__query_builder::Table<Skills> {
        __sdk::__query_builder::Table::new("skills")
    }
}
