// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Skills {
    pub person_id: u64,
    pub engineering: f32,
    pub medical: f32,
    pub piloting: f32,
    pub science: f32,
    pub social: f32,
    pub combat: f32,
}

impl __sdk::InModule for Skills {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Skills`.
///
/// Provides typed access to columns for query building.
pub struct SkillsCols {
    pub person_id: __sdk::__query_builder::Col<Skills, u64>,
    pub engineering: __sdk::__query_builder::Col<Skills, f32>,
    pub medical: __sdk::__query_builder::Col<Skills, f32>,
    pub piloting: __sdk::__query_builder::Col<Skills, f32>,
    pub science: __sdk::__query_builder::Col<Skills, f32>,
    pub social: __sdk::__query_builder::Col<Skills, f32>,
    pub combat: __sdk::__query_builder::Col<Skills, f32>,
}

impl __sdk::__query_builder::HasCols for Skills {
    type Cols = SkillsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SkillsCols {
            person_id: __sdk::__query_builder::Col::new(table_name, "person_id"),
            engineering: __sdk::__query_builder::Col::new(table_name, "engineering"),
            medical: __sdk::__query_builder::Col::new(table_name, "medical"),
            piloting: __sdk::__query_builder::Col::new(table_name, "piloting"),
            science: __sdk::__query_builder::Col::new(table_name, "science"),
            social: __sdk::__query_builder::Col::new(table_name, "social"),
            combat: __sdk::__query_builder::Col::new(table_name, "combat"),
        }
    }
}

/// Indexed column accessor struct for the table `Skills`.
///
/// Provides typed access to indexed columns for query building.
pub struct SkillsIxCols {
    pub person_id: __sdk::__query_builder::IxCol<Skills, u64>,
}

impl __sdk::__query_builder::HasIxCols for Skills {
    type IxCols = SkillsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SkillsIxCols {
            person_id: __sdk::__query_builder::IxCol::new(table_name, "person_id"),
        }
    }
}
