// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Subsystem {
    pub id: u64,
    pub system_id: u64,
    pub name: String,
    pub subsystem_type: u8,
    pub health: f32,
    pub status: u8,
    pub node_id: u64,
    pub power_draw: f32,
    pub crew_required: u8,
}

impl __sdk::InModule for Subsystem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Subsystem`.
///
/// Provides typed access to columns for query building.
pub struct SubsystemCols {
    pub id: __sdk::__query_builder::Col<Subsystem, u64>,
    pub system_id: __sdk::__query_builder::Col<Subsystem, u64>,
    pub name: __sdk::__query_builder::Col<Subsystem, String>,
    pub subsystem_type: __sdk::__query_builder::Col<Subsystem, u8>,
    pub health: __sdk::__query_builder::Col<Subsystem, f32>,
    pub status: __sdk::__query_builder::Col<Subsystem, u8>,
    pub node_id: __sdk::__query_builder::Col<Subsystem, u64>,
    pub power_draw: __sdk::__query_builder::Col<Subsystem, f32>,
    pub crew_required: __sdk::__query_builder::Col<Subsystem, u8>,
}

impl __sdk::__query_builder::HasCols for Subsystem {
    type Cols = SubsystemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SubsystemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            system_id: __sdk::__query_builder::Col::new(table_name, "system_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            subsystem_type: __sdk::__query_builder::Col::new(table_name, "subsystem_type"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            power_draw: __sdk::__query_builder::Col::new(table_name, "power_draw"),
            crew_required: __sdk::__query_builder::Col::new(table_name, "crew_required"),
        }
    }
}

/// Indexed column accessor struct for the table `Subsystem`.
///
/// Provides typed access to indexed columns for query building.
pub struct SubsystemIxCols {
    pub id: __sdk::__query_builder::IxCol<Subsystem, u64>,
}

impl __sdk::__query_builder::HasIxCols for Subsystem {
    type IxCols = SubsystemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SubsystemIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
