// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::subsystem_type::Subsystem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `subsystem`.
///
/// Obtain a handle from the [`SubsystemTableAccess::subsystem`] method on [`super::RemoteTables`],
/// like `ctx.db.subsystem()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subsystem().on_insert(...)`.
pub struct SubsystemTableHandle<'ctx> {
    imp: __sdk::TableHandle<Subsystem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `subsystem`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SubsystemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SubsystemTableHandle`], which mediates access to the table `subsystem`.
    fn subsystem(&self) -> SubsystemTableHandle<'_>;
}

impl SubsystemTableAccess for super::RemoteTables {
    fn subsystem(&self) -> SubsystemTableHandle<'_> {
        SubsystemTableHandle {
            imp: self.imp.get_table::<Subsystem>("subsystem"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SubsystemInsertCallbackId(__sdk::CallbackId);
pub struct SubsystemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SubsystemTableHandle<'ctx> {
    type Row = Subsystem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Subsystem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SubsystemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubsystemInsertCallbackId {
        SubsystemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SubsystemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SubsystemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubsystemDeleteCallbackId {
        SubsystemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SubsystemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Subsystem>("subsystem");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct SubsystemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SubsystemTableHandle<'ctx> {
    type UpdateCallbackId = SubsystemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SubsystemUpdateCallbackId {
        SubsystemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SubsystemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Subsystem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Subsystem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `subsystem`,
/// which allows point queries on the field of the same name
/// via the [`SubsystemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subsystem().id().find(...)`.
pub struct SubsystemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Subsystem, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SubsystemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `subsystem`.
    pub fn id(&self) -> SubsystemIdUnique<'ctx> {
        SubsystemIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SubsystemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Subsystem> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Subsystem`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait subsystemQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Subsystem`.
    fn subsystem(&self) -> __sdk::__query_builder::Table<Subsystem>;
}

impl subsystemQueryTableAccess for __sdk::QueryTableAccessor {
    fn subsystem(&self) -> __sdk::__query_builder::Table<Subsystem> {
        __sdk::__query_builder::Table::new("subsystem")
    }
}
