// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::system_component_type::SystemComponent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `system_component`.
///
/// Obtain a handle from the [`SystemComponentTableAccess::system_component`] method on [`super::RemoteTables`],
/// like `ctx.db.system_component()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.system_component().on_insert(...)`.
pub struct SystemComponentTableHandle<'ctx> {
    imp: __sdk::TableHandle<SystemComponent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `system_component`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SystemComponentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SystemComponentTableHandle`], which mediates access to the table `system_component`.
    fn system_component(&self) -> SystemComponentTableHandle<'_>;
}

impl SystemComponentTableAccess for super::RemoteTables {
    fn system_component(&self) -> SystemComponentTableHandle<'_> {
        SystemComponentTableHandle {
            imp: self.imp.get_table::<SystemComponent>("system_component"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SystemComponentInsertCallbackId(__sdk::CallbackId);
pub struct SystemComponentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SystemComponentTableHandle<'ctx> {
    type Row = SystemComponent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SystemComponent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SystemComponentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SystemComponentInsertCallbackId {
        SystemComponentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SystemComponentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SystemComponentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SystemComponentDeleteCallbackId {
        SystemComponentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SystemComponentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SystemComponent>("system_component");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct SystemComponentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SystemComponentTableHandle<'ctx> {
    type UpdateCallbackId = SystemComponentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SystemComponentUpdateCallbackId {
        SystemComponentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SystemComponentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SystemComponent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SystemComponent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `system_component`,
/// which allows point queries on the field of the same name
/// via the [`SystemComponentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.system_component().id().find(...)`.
pub struct SystemComponentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SystemComponent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SystemComponentTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `system_component`.
    pub fn id(&self) -> SystemComponentIdUnique<'ctx> {
        SystemComponentIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SystemComponentIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SystemComponent> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SystemComponent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait system_componentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SystemComponent`.
    fn system_component(&self) -> __sdk::__query_builder::Table<SystemComponent>;
}

impl system_componentQueryTableAccess for __sdk::QueryTableAccessor {
    fn system_component(&self) -> __sdk::__query_builder::Table<SystemComponent> {
        __sdk::__query_builder::Table::new("system_component")
    }
}
