// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SystemComponent {
    pub id: u64,
    pub subsystem_id: u64,
    pub name: String,
    pub component_type: u8,
    pub health: f32,
    pub status: u8,
    pub position_x: f32,
    pub position_y: f32,
    pub maintenance_interval_hours: f32,
    pub last_maintenance: f64,
}

impl __sdk::InModule for SystemComponent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SystemComponent`.
///
/// Provides typed access to columns for query building.
pub struct SystemComponentCols {
    pub id: __sdk::__query_builder::Col<SystemComponent, u64>,
    pub subsystem_id: __sdk::__query_builder::Col<SystemComponent, u64>,
    pub name: __sdk::__query_builder::Col<SystemComponent, String>,
    pub component_type: __sdk::__query_builder::Col<SystemComponent, u8>,
    pub health: __sdk::__query_builder::Col<SystemComponent, f32>,
    pub status: __sdk::__query_builder::Col<SystemComponent, u8>,
    pub position_x: __sdk::__query_builder::Col<SystemComponent, f32>,
    pub position_y: __sdk::__query_builder::Col<SystemComponent, f32>,
    pub maintenance_interval_hours: __sdk::__query_builder::Col<SystemComponent, f32>,
    pub last_maintenance: __sdk::__query_builder::Col<SystemComponent, f64>,
}

impl __sdk::__query_builder::HasCols for SystemComponent {
    type Cols = SystemComponentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SystemComponentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            subsystem_id: __sdk::__query_builder::Col::new(table_name, "subsystem_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            component_type: __sdk::__query_builder::Col::new(table_name, "component_type"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            position_x: __sdk::__query_builder::Col::new(table_name, "position_x"),
            position_y: __sdk::__query_builder::Col::new(table_name, "position_y"),
            maintenance_interval_hours: __sdk::__query_builder::Col::new(
                table_name,
                "maintenance_interval_hours",
            ),
            last_maintenance: __sdk::__query_builder::Col::new(table_name, "last_maintenance"),
        }
    }
}

/// Indexed column accessor struct for the table `SystemComponent`.
///
/// Provides typed access to indexed columns for query building.
pub struct SystemComponentIxCols {
    pub id: __sdk::__query_builder::IxCol<SystemComponent, u64>,
}

impl __sdk::__query_builder::HasIxCols for SystemComponent {
    type IxCols = SystemComponentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SystemComponentIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
