// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ToggleDoorArgs {
    pub door_id: u64,
}

impl From<ToggleDoorArgs> for super::Reducer {
    fn from(args: ToggleDoorArgs) -> Self {
        Self::ToggleDoor {
            door_id: args.door_id,
        }
    }
}

impl __sdk::InModule for ToggleDoorArgs {
    type Module = super::RemoteModule;
}

pub struct ToggleDoorCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `toggle_door`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait toggle_door {
    /// Request that the remote module invoke the reducer `toggle_door` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_toggle_door`] callbacks.
    fn toggle_door(&self, door_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `toggle_door`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ToggleDoorCallbackId`] can be passed to [`Self::remove_on_toggle_door`]
    /// to cancel the callback.
    fn on_toggle_door(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> ToggleDoorCallbackId;
    /// Cancel a callback previously registered by [`Self::on_toggle_door`],
    /// causing it not to run in the future.
    fn remove_on_toggle_door(&self, callback: ToggleDoorCallbackId);
}

impl toggle_door for super::RemoteReducers {
    fn toggle_door(&self, door_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("toggle_door", ToggleDoorArgs { door_id })
    }
    fn on_toggle_door(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> ToggleDoorCallbackId {
        ToggleDoorCallbackId(self.imp.on_reducer(
            "toggle_door",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ToggleDoor { door_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, door_id)
            }),
        ))
    }
    fn remove_on_toggle_door(&self, callback: ToggleDoorCallbackId) {
        self.imp.remove_on_reducer("toggle_door", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `toggle_door`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_toggle_door {
    /// Set the call-reducer flags for the reducer `toggle_door` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn toggle_door(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_toggle_door for super::SetReducerFlags {
    fn toggle_door(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("toggle_door", flags);
    }
}
