// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::vertical_shaft_type::VerticalShaft;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `vertical_shaft`.
///
/// Obtain a handle from the [`VerticalShaftTableAccess::vertical_shaft`] method on [`super::RemoteTables`],
/// like `ctx.db.vertical_shaft()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.vertical_shaft().on_insert(...)`.
pub struct VerticalShaftTableHandle<'ctx> {
    imp: __sdk::TableHandle<VerticalShaft>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `vertical_shaft`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VerticalShaftTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VerticalShaftTableHandle`], which mediates access to the table `vertical_shaft`.
    fn vertical_shaft(&self) -> VerticalShaftTableHandle<'_>;
}

impl VerticalShaftTableAccess for super::RemoteTables {
    fn vertical_shaft(&self) -> VerticalShaftTableHandle<'_> {
        VerticalShaftTableHandle {
            imp: self.imp.get_table::<VerticalShaft>("vertical_shaft"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VerticalShaftInsertCallbackId(__sdk::CallbackId);
pub struct VerticalShaftDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VerticalShaftTableHandle<'ctx> {
    type Row = VerticalShaft;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VerticalShaft> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VerticalShaftInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VerticalShaftInsertCallbackId {
        VerticalShaftInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VerticalShaftInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VerticalShaftDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VerticalShaftDeleteCallbackId {
        VerticalShaftDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VerticalShaftDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VerticalShaft>("vertical_shaft");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct VerticalShaftUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VerticalShaftTableHandle<'ctx> {
    type UpdateCallbackId = VerticalShaftUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VerticalShaftUpdateCallbackId {
        VerticalShaftUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VerticalShaftUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<VerticalShaft>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VerticalShaft>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `vertical_shaft`,
/// which allows point queries on the field of the same name
/// via the [`VerticalShaftIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.vertical_shaft().id().find(...)`.
pub struct VerticalShaftIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VerticalShaft, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VerticalShaftTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `vertical_shaft`.
    pub fn id(&self) -> VerticalShaftIdUnique<'ctx> {
        VerticalShaftIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VerticalShaftIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<VerticalShaft> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VerticalShaft`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait vertical_shaftQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VerticalShaft`.
    fn vertical_shaft(&self) -> __sdk::__query_builder::Table<VerticalShaft>;
}

impl vertical_shaftQueryTableAccess for __sdk::QueryTableAccessor {
    fn vertical_shaft(&self) -> __sdk::__query_builder::Table<VerticalShaft> {
        __sdk::__query_builder::Table::new("vertical_shaft")
    }
}
