// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct VerticalShaft {
    pub id: u64,
    pub shaft_type: u8,
    pub name: String,
    pub x: f32,
    pub y: f32,
    pub decks_served: String,
    pub width: f32,
    pub height: f32,
}

impl __sdk::InModule for VerticalShaft {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `VerticalShaft`.
///
/// Provides typed access to columns for query building.
pub struct VerticalShaftCols {
    pub id: __sdk::__query_builder::Col<VerticalShaft, u64>,
    pub shaft_type: __sdk::__query_builder::Col<VerticalShaft, u8>,
    pub name: __sdk::__query_builder::Col<VerticalShaft, String>,
    pub x: __sdk::__query_builder::Col<VerticalShaft, f32>,
    pub y: __sdk::__query_builder::Col<VerticalShaft, f32>,
    pub decks_served: __sdk::__query_builder::Col<VerticalShaft, String>,
    pub width: __sdk::__query_builder::Col<VerticalShaft, f32>,
    pub height: __sdk::__query_builder::Col<VerticalShaft, f32>,
}

impl __sdk::__query_builder::HasCols for VerticalShaft {
    type Cols = VerticalShaftCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        VerticalShaftCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            shaft_type: __sdk::__query_builder::Col::new(table_name, "shaft_type"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            decks_served: __sdk::__query_builder::Col::new(table_name, "decks_served"),
            width: __sdk::__query_builder::Col::new(table_name, "width"),
            height: __sdk::__query_builder::Col::new(table_name, "height"),
        }
    }
}

/// Indexed column accessor struct for the table `VerticalShaft`.
///
/// Provides typed access to indexed columns for query building.
pub struct VerticalShaftIxCols {
    pub id: __sdk::__query_builder::IxCol<VerticalShaft, u64>,
}

impl __sdk::__query_builder::HasIxCols for VerticalShaft {
    type IxCols = VerticalShaftIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        VerticalShaftIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
