//! Facility specifications and deck zoning logic.
//!
//! Defines FacilitySpec and zone-to-deck mapping functions.

use crate::tables::groups;
use crate::tables::room_types;

/// Facility manifest entry — describes one kind of room to instantiate.
pub struct FacilitySpec {
    pub name: &'static str,
    pub room_type: u8,
    pub target_area: f32,
    pub capacity: u32,
    pub count: u32,
    pub deck_zone: u8, // 0=command, 1=hab, 2=services, 3=rec, 4=lifesup, 5=cargo, 6=eng
    pub group: u8,
}

/// Deck-zone → deck range mapping.
pub fn deck_range_for_zone(zone: u8, deck_count: u32) -> (u32, u32) {
    let dc = deck_count;
    match zone {
        0 => (0, core::cmp::min(2, dc)),
        1 => (2, core::cmp::min(10, dc)),
        2 => (
            core::cmp::min(10, dc.saturating_sub(1)),
            core::cmp::min(12, dc),
        ),
        3 => (
            core::cmp::min(12, dc.saturating_sub(1)),
            core::cmp::min(16, dc),
        ),
        4 => (
            core::cmp::min(16, dc.saturating_sub(1)),
            core::cmp::min(18, dc),
        ),
        5 => (
            core::cmp::min(18, dc.saturating_sub(1)),
            core::cmp::min(20, dc),
        ),
        6 => (core::cmp::max(dc.saturating_sub(2), 0), dc),
        _ => (0, dc),
    }
}

/// Returns the facility manifest with all room specs for ship generation.
pub fn get_facility_manifest() -> Vec<FacilitySpec> {
    vec![
        // === COMMAND (zone 0) ===
        FacilitySpec {
            name: "Bridge",
            room_type: room_types::BRIDGE,
            target_area: 200.0,
            capacity: 10,
            count: 1,
            deck_zone: 0,
            group: groups::COMMAND,
        },
        FacilitySpec {
            name: "CIC",
            room_type: room_types::CIC,
            target_area: 50.0,
            capacity: 8,
            count: 1,
            deck_zone: 0,
            group: groups::COMMAND,
        },
        FacilitySpec {
            name: "Conference Room",
            room_type: room_types::CONFERENCE,
            target_area: 45.0,
            capacity: 12,
            count: 4,
            deck_zone: 0,
            group: groups::COMMAND,
        },
        FacilitySpec {
            name: "Captain's Ready Room",
            room_type: room_types::CAPTAINS_READY_ROOM,
            target_area: 35.0,
            capacity: 2,
            count: 1,
            deck_zone: 0,
            group: groups::COMMAND,
        },
        FacilitySpec {
            name: "Observatory",
            room_type: room_types::OBSERVATORY,
            target_area: 80.0,
            capacity: 6,
            count: 1,
            deck_zone: 0,
            group: groups::COMMAND,
        },
        FacilitySpec {
            name: "Comms Room",
            room_type: room_types::COMMS_ROOM,
            target_area: 35.0,
            capacity: 4,
            count: 1,
            deck_zone: 0,
            group: groups::COMMAND,
        },
        FacilitySpec {
            name: "Security Office",
            room_type: room_types::SECURITY_OFFICE,
            target_area: 45.0,
            capacity: 6,
            count: 2,
            deck_zone: 0,
            group: groups::COMMAND,
        },
        FacilitySpec {
            name: "Admin Office",
            room_type: room_types::ADMIN_OFFICE,
            target_area: 45.0,
            capacity: 8,
            count: 2,
            deck_zone: 0,
            group: groups::COMMAND,
        },
        FacilitySpec {
            name: "Brig",
            room_type: room_types::BRIG,
            target_area: 40.0,
            capacity: 4,
            count: 1,
            deck_zone: 0,
            group: groups::COMMAND,
        },
        FacilitySpec {
            name: "Armory",
            room_type: room_types::ARMORY,
            target_area: 50.0,
            capacity: 4,
            count: 2,
            deck_zone: 0,
            group: groups::COMMAND,
        },
        // === HABITATION (zone 1) ===
        FacilitySpec {
            name: "Crew Quarters",
            room_type: room_types::QUARTERS_CREW,
            target_area: 20.0,
            capacity: 2,
            count: 150,
            deck_zone: 1,
            group: groups::PASSENGER,
        },
        FacilitySpec {
            name: "Officer Quarters",
            room_type: room_types::QUARTERS_OFFICER,
            target_area: 22.0,
            capacity: 1,
            count: 30,
            deck_zone: 1,
            group: groups::PASSENGER,
        },
        FacilitySpec {
            name: "Passenger Quarters",
            room_type: room_types::QUARTERS_PASSENGER,
            target_area: 35.0,
            capacity: 2,
            count: 200,
            deck_zone: 1,
            group: groups::PASSENGER,
        },
        FacilitySpec {
            name: "VIP Suite",
            room_type: room_types::VIP_SUITE,
            target_area: 55.0,
            capacity: 1,
            count: 5,
            deck_zone: 1,
            group: groups::PASSENGER,
        },
        FacilitySpec {
            name: "Family Suite",
            room_type: room_types::FAMILY_SUITE,
            target_area: 35.0,
            capacity: 4,
            count: 20,
            deck_zone: 1,
            group: groups::PASSENGER,
        },
        FacilitySpec {
            name: "Shared Bathroom",
            room_type: room_types::SHARED_BATHROOM,
            target_area: 9.0,
            capacity: 4,
            count: 40,
            deck_zone: 1,
            group: groups::PASSENGER,
        },
        FacilitySpec {
            name: "Shared Laundry",
            room_type: room_types::SHARED_LAUNDRY,
            target_area: 18.0,
            capacity: 8,
            count: 15,
            deck_zone: 1,
            group: groups::PASSENGER,
        },
        // === FOOD & DINING (zone 2) ===
        FacilitySpec {
            name: "Mess Hall",
            room_type: room_types::MESS_HALL,
            target_area: 500.0,
            capacity: 150,
            count: 2,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Galley",
            room_type: room_types::GALLEY,
            target_area: 120.0,
            capacity: 10,
            count: 2,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Cafe",
            room_type: room_types::CAFE,
            target_area: 50.0,
            capacity: 20,
            count: 4,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Bar",
            room_type: room_types::BAR,
            target_area: 50.0,
            capacity: 30,
            count: 3,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Food Storage (Cold)",
            room_type: room_types::FOOD_STORAGE_COLD,
            target_area: 120.0,
            capacity: 0,
            count: 3,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Food Storage (Dry)",
            room_type: room_types::FOOD_STORAGE_DRY,
            target_area: 120.0,
            capacity: 0,
            count: 3,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Bakery",
            room_type: room_types::BAKERY,
            target_area: 40.0,
            capacity: 5,
            count: 1,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Hydroponics",
            room_type: room_types::HYDROPONICS,
            target_area: 1000.0,
            capacity: 15,
            count: 2,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        // === MEDICAL (zone 2) ===
        FacilitySpec {
            name: "Hospital Ward",
            room_type: room_types::HOSPITAL_WARD,
            target_area: 200.0,
            capacity: 40,
            count: 2,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Surgery",
            room_type: room_types::SURGERY,
            target_area: 55.0,
            capacity: 4,
            count: 2,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Pharmacy",
            room_type: room_types::PHARMACY,
            target_area: 35.0,
            capacity: 4,
            count: 2,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Dental Clinic",
            room_type: room_types::DENTAL_CLINIC,
            target_area: 35.0,
            capacity: 3,
            count: 1,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Mental Health",
            room_type: room_types::MENTAL_HEALTH,
            target_area: 35.0,
            capacity: 3,
            count: 2,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Medbay",
            room_type: room_types::MEDBAY,
            target_area: 35.0,
            capacity: 8,
            count: 4,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Quarantine",
            room_type: room_types::QUARANTINE,
            target_area: 200.0,
            capacity: 20,
            count: 1,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Morgue",
            room_type: room_types::MORGUE,
            target_area: 35.0,
            capacity: 0,
            count: 1,
            deck_zone: 2,
            group: groups::COMMONS,
        },
        // === RECREATION (zone 3) ===
        FacilitySpec {
            name: "Arboretum",
            room_type: room_types::ARBORETUM,
            target_area: 800.0,
            capacity: 100,
            count: 1,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Gym",
            room_type: room_types::GYM,
            target_area: 250.0,
            capacity: 40,
            count: 3,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Pool",
            room_type: room_types::POOL,
            target_area: 250.0,
            capacity: 30,
            count: 1,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Library",
            room_type: room_types::LIBRARY,
            target_area: 120.0,
            capacity: 20,
            count: 2,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Theatre",
            room_type: room_types::THEATRE,
            target_area: 350.0,
            capacity: 100,
            count: 1,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Game Room",
            room_type: room_types::GAME_ROOM,
            target_area: 50.0,
            capacity: 20,
            count: 5,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Observation Lounge",
            room_type: room_types::OBSERVATION_LOUNGE,
            target_area: 120.0,
            capacity: 40,
            count: 3,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Art Studio",
            room_type: room_types::ART_STUDIO,
            target_area: 50.0,
            capacity: 12,
            count: 2,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Music Room",
            room_type: room_types::MUSIC_ROOM,
            target_area: 50.0,
            capacity: 12,
            count: 2,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Chapel",
            room_type: room_types::CHAPEL,
            target_area: 60.0,
            capacity: 30,
            count: 1,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Holodeck",
            room_type: room_types::HOLODECK,
            target_area: 60.0,
            capacity: 10,
            count: 4,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Nursery",
            room_type: room_types::NURSERY,
            target_area: 60.0,
            capacity: 20,
            count: 2,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "School",
            room_type: room_types::SCHOOL,
            target_area: 60.0,
            capacity: 30,
            count: 3,
            deck_zone: 3,
            group: groups::COMMONS,
        },
        // === LIFE SUPPORT & INFRASTRUCTURE (zone 4) ===
        FacilitySpec {
            name: "Life Support",
            room_type: room_types::LIFE_SUPPORT,
            target_area: 200.0,
            capacity: 6,
            count: 1,
            deck_zone: 4,
            group: groups::LIFE_SUPPORT,
        },
        FacilitySpec {
            name: "Atmosphere Processing",
            room_type: room_types::ATMOSPHERE_PROCESSING,
            target_area: 200.0,
            capacity: 4,
            count: 2,
            deck_zone: 4,
            group: groups::LIFE_SUPPORT,
        },
        FacilitySpec {
            name: "Water Recycling",
            room_type: room_types::WATER_RECYCLING,
            target_area: 200.0,
            capacity: 4,
            count: 2,
            deck_zone: 4,
            group: groups::LIFE_SUPPORT,
        },
        FacilitySpec {
            name: "Waste Processing",
            room_type: room_types::WASTE_PROCESSING,
            target_area: 200.0,
            capacity: 4,
            count: 2,
            deck_zone: 4,
            group: groups::LIFE_SUPPORT,
        },
        FacilitySpec {
            name: "Environmental Monitoring",
            room_type: room_types::ENV_MONITORING,
            target_area: 50.0,
            capacity: 4,
            count: 1,
            deck_zone: 4,
            group: groups::LIFE_SUPPORT,
        },
        FacilitySpec {
            name: "HVAC Control",
            room_type: room_types::HVAC_CONTROL,
            target_area: 80.0,
            capacity: 3,
            count: 1,
            deck_zone: 4,
            group: groups::LIFE_SUPPORT,
        },
        FacilitySpec {
            name: "Cooling Plant",
            room_type: room_types::COOLING_PLANT,
            target_area: 150.0,
            capacity: 3,
            count: 1,
            deck_zone: 4,
            group: groups::LIFE_SUPPORT,
        },
        // === CARGO & STORAGE (zone 5) ===
        FacilitySpec {
            name: "Cargo Bay",
            room_type: room_types::CARGO_BAY,
            target_area: 500.0,
            capacity: 10,
            count: 4,
            deck_zone: 5,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Storage",
            room_type: room_types::STORAGE,
            target_area: 120.0,
            capacity: 0,
            count: 10,
            deck_zone: 5,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Parts Storage",
            room_type: room_types::PARTS_STORAGE,
            target_area: 120.0,
            capacity: 0,
            count: 5,
            deck_zone: 5,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Shuttle Bay",
            room_type: room_types::SHUTTLE_BAY,
            target_area: 500.0,
            capacity: 6,
            count: 2,
            deck_zone: 5,
            group: groups::COMMONS,
        },
        FacilitySpec {
            name: "Airlock",
            room_type: room_types::AIRLOCK,
            target_area: 40.0,
            capacity: 8,
            count: 6,
            deck_zone: 5,
            group: groups::COMMONS,
        },
        // === ENGINEERING (zone 6) ===
        FacilitySpec {
            name: "Engineering",
            room_type: room_types::ENGINEERING,
            target_area: 200.0,
            capacity: 15,
            count: 1,
            deck_zone: 6,
            group: groups::ENGINEERING,
        },
        FacilitySpec {
            name: "Reactor",
            room_type: room_types::REACTOR,
            target_area: 200.0,
            capacity: 6,
            count: 1,
            deck_zone: 6,
            group: groups::ENGINEERING,
        },
        FacilitySpec {
            name: "Backup Reactor",
            room_type: room_types::BACKUP_REACTOR,
            target_area: 250.0,
            capacity: 4,
            count: 1,
            deck_zone: 6,
            group: groups::ENGINEERING,
        },
        FacilitySpec {
            name: "Engine Room",
            room_type: room_types::ENGINE_ROOM,
            target_area: 500.0,
            capacity: 12,
            count: 1,
            deck_zone: 6,
            group: groups::ENGINEERING,
        },
        FacilitySpec {
            name: "Power Distribution",
            room_type: room_types::POWER_DISTRIBUTION,
            target_area: 100.0,
            capacity: 3,
            count: 2,
            deck_zone: 6,
            group: groups::ENGINEERING,
        },
        FacilitySpec {
            name: "Fuel Storage",
            room_type: room_types::FUEL_STORAGE,
            target_area: 250.0,
            capacity: 0,
            count: 2,
            deck_zone: 6,
            group: groups::ENGINEERING,
        },
        FacilitySpec {
            name: "Machine Shop",
            room_type: room_types::MACHINE_SHOP,
            target_area: 100.0,
            capacity: 8,
            count: 2,
            deck_zone: 6,
            group: groups::ENGINEERING,
        },
        FacilitySpec {
            name: "Robotics Bay",
            room_type: room_types::ROBOTICS_BAY,
            target_area: 55.0,
            capacity: 6,
            count: 1,
            deck_zone: 6,
            group: groups::ENGINEERING,
        },
        FacilitySpec {
            name: "Electronics Lab",
            room_type: room_types::ELECTRONICS_LAB,
            target_area: 55.0,
            capacity: 6,
            count: 1,
            deck_zone: 6,
            group: groups::ENGINEERING,
        },
        FacilitySpec {
            name: "Laboratory",
            room_type: room_types::LABORATORY,
            target_area: 80.0,
            capacity: 8,
            count: 3,
            deck_zone: 6,
            group: groups::ENGINEERING,
        },
    ]
}
